# Generated by Django 4.0 on 2022-03-16 04:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], default='Hadir', max_length=255)),
                ('FILE_KETERANGAN', models.FileField(blank=True, max_length=255, upload_to='AbsensiEkskul')),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DaftarJurnalEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('HARI', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jum`at', 'Jum`at'), ('Sabtu', 'Sabtu')], max_length=255)),
                ('WAKTU_MULAI', models.TimeField()),
                ('WAKTU_BERAKHIR', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JurnalEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PERTEMUAN', models.CharField(max_length=255)),
                ('TANGGAL_MELATIH', models.DateField(default=datetime.date.today)),
                ('DESKRIPSI_KEGIATAN', models.TextField()),
                ('FILE_DOKUMENTASI', models.FileField(max_length=255, upload_to='JurnalEkskul')),
            ],
        ),
        migrations.CreateModel(
            name='KatalogEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
                ('KATEGORI', models.CharField(choices=[('Wajib', 'Wajib'), ('Pilihan', 'Pilihan'), ('Mandiri', 'Mandiri')], max_length=255)),
                ('DESKRIPSI', models.CharField(max_length=255)),
                ('DOKUMENTASI', models.ImageField(blank=True, max_length=255, upload_to='KatalogEkskul')),
            ],
        ),
        migrations.CreateModel(
            name='KategoriProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategori Program Kebaikan',
                'ordering': ['NAMA'],
            },
        ),
        migrations.CreateModel(
            name='NilaiEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PREDIKAT', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=255)),
                ('DESKRIPSI', models.TextField(max_length=1020)),
            ],
        ),
        migrations.CreateModel(
            name='PelanggaranSiswa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('POIN', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pelanggaran Siswa',
            },
        ),
        migrations.CreateModel(
            name='PengajuanEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_PENGAJUAN', models.DateField(default=datetime.date.today)),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pengajuan', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanLaporanPelanggaran',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BUKTI_PELANGGARAN', models.FileField(max_length=255, upload_to='BuktiPelanggaran')),
                ('TANGGAL_PENGAJUAN', models.DateTimeField(default=django.utils.timezone.now)),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pengajuan Laporan Pelanggaran',
            },
        ),
        migrations.CreateModel(
            name='PengajuanProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BUKTI_PROGRAM_KEBAIKAN', models.FileField(max_length=255, upload_to='BuktiProgramKebaikan')),
                ('TANGGAL_PENGAJUAN', models.DateTimeField(default=django.utils.timezone.now)),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pengajuan Program Kebaikan',
            },
        ),
        migrations.CreateModel(
            name='PoinProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('POIN', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Poin Program Kebaikan',
                'ordering': ['KETERANGAN'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BUKTI_PROGRAM_KEBAIKAN', models.FileField(max_length=255, upload_to='BuktiProgramKebaikan')),
                ('TANGGAL_PENGAJUAN', models.DateTimeField(default=django.utils.timezone.now)),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('DATA_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
                ('JENIS_PROGRAM_KEBAIKAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.poinprogramkebaikan')),
            ],
            options={
                'verbose_name_plural': 'Riwayat Program Kebaikan',
            },
        ),
        migrations.CreateModel(
            name='RiwayatLaporanPelanggaran',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BUKTI_PELANGGARAN', models.FileField(max_length=255, upload_to='BuktiPelanggaran')),
                ('TANGGAL_PENGAJUAN', models.DateTimeField(default=django.utils.timezone.now)),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('DATA_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
                ('JENIS_PELANGGARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.poinpelanggaran')),
            ],
            options={
                'verbose_name_plural': 'Riwayat Laporan Pelanggaran',
            },
        ),
        migrations.CreateModel(
            name='ProgramKerjaEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FILE_PROGRAM_KERJA', models.FileField(max_length=255, upload_to='ProgramKerjaEkskul')),
                ('EKSKUL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul')),
                ('PELATIH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih')),
                ('TAHUN_AJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('KATEGORI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.kategoriprogramkebaikan')),
            ],
            options={
                'verbose_name_plural': 'Program Kebaikan',
                'ordering': ['KETERANGAN'],
            },
        ),
        migrations.AddConstraint(
            model_name='poinprogramkebaikan',
            constraint=models.UniqueConstraint(fields=('KETERANGAN', 'POIN'), name='kesiswaan_poinprogramkebaikan_unique'),
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='DATA_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='JENIS_PROGRAM_KEBAIKAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.poinprogramkebaikan'),
        ),
        migrations.AddField(
            model_name='pengajuanlaporanpelanggaran',
            name='DATA_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='pengajuanlaporanpelanggaran',
            name='JENIS_PELANGGARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.poinpelanggaran'),
        ),
        migrations.AddField(
            model_name='pengajuanekskul',
            name='EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='pengajuanekskul',
            name='KELAS_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
        migrations.AddField(
            model_name='pengajuanekskul',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
        ),
        migrations.AddField(
            model_name='pelanggaransiswa',
            name='DATA_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='nilaiekskul',
            name='DATA_ANGGOTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.anggotaekskul'),
        ),
        migrations.AddField(
            model_name='nilaiekskul',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AddConstraint(
            model_name='kategoriprogramkebaikan',
            constraint=models.UniqueConstraint(fields=('NAMA',), name='kesiswaan_kategoriprogramkebaikan_unique'),
        ),
        migrations.AddField(
            model_name='jurnalekskul',
            name='DAFTAR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.daftarjurnalekskul'),
        ),
        migrations.AddField(
            model_name='jurnalekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='EKSKUL',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='JADWAL_EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.jadwalekskul'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AddField(
            model_name='anggotaekskul',
            name='EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='anggotaekskul',
            name='KELAS_SISWA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
        migrations.AddField(
            model_name='anggotaekskul',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
        ),
        migrations.AddField(
            model_name='absensiekskul',
            name='JURNAL_EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.jurnalekskul'),
        ),
        migrations.AddField(
            model_name='absensiekskul',
            name='NIS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddConstraint(
            model_name='programkerjaekskul',
            constraint=models.UniqueConstraint(fields=('PELATIH', 'EKSKUL', 'TAHUN_AJARAN'), name='kesiswaan_programkerjaekskul_unique'),
        ),
        migrations.AddConstraint(
            model_name='programkebaikan',
            constraint=models.UniqueConstraint(fields=('KETERANGAN',), name='kesiswaan_programkebaikan_unique'),
        ),
        migrations.AddConstraint(
            model_name='jadwalekskul',
            constraint=models.UniqueConstraint(fields=('PELATIH', 'EKSKUL', 'HARI', 'TAHUN_AJARAN', 'WAKTU_MULAI', 'WAKTU_BERAKHIR'), name='kesiswaan_jadwalekskul_unique'),
        ),
    ]