# Generated by Django 4.0 on 2022-01-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0078_absensisiswa'),
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
        ('kesiswaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatLaporanPelanggaran',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BUKTI_PELANGGARAN', models.FileField(max_length=255, upload_to='BuktiPelanggaran')),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('JENIS_PELANGGARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.poinpelanggaran')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
        ),
    ]
