# Generated by Django 4.0 on 2022-02-18 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanlaporanpelanggaran',
            name='TANGGAL_PENGAJUAN',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='TANGGAL_PENGAJUAN',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riwayatlaporanpelanggaran',
            name='TANGGAL_PENGAJUAN',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riwayatprogramkebaikan',
            name='TANGGAL_PENGAJUAN',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
