# Generated by Django 4.0 on 2022-04-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaiekskul',
            name='SEMESTER',
        ),
    ]
