# Generated by Django 4.0 on 2022-03-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('kesiswaan', '0001_initial'),
        ('kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatlaporanpelanggaran',
            name='JENIS_PELANGGARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.poinpelanggaran'),
        ),
        migrations.AddField(
            model_name='programkerjaekskul',
            name='EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='programkerjaekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='programkerjaekskul',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
        ),
        migrations.AddField(
            model_name='programkebaikan',
            name='KATEGORI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.kategoriprogramkebaikan'),
        ),
        migrations.AddConstraint(
            model_name='poinprogramkebaikan',
            constraint=models.UniqueConstraint(fields=('KETERANGAN', 'POIN'), name='kesiswaan_poinprogramkebaikan_unique'),
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='DATA_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='JENIS_PROGRAM_KEBAIKAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.poinprogramkebaikan'),
        ),
        migrations.AddField(
            model_name='pengajuanlaporanpelanggaran',
            name='DATA_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='pengajuanlaporanpelanggaran',
            name='JENIS_PELANGGARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.poinpelanggaran'),
        ),
        migrations.AddField(
            model_name='pengajuanekskul',
            name='EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='pengajuanekskul',
            name='KELAS_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
        migrations.AddField(
            model_name='pengajuanekskul',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
        ),
        migrations.AddField(
            model_name='pelanggaransiswa',
            name='DATA_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='nilaiekskul',
            name='DATA_ANGGOTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.anggotaekskul'),
        ),
        migrations.AddField(
            model_name='nilaiekskul',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AddConstraint(
            model_name='kategoriprogramkebaikan',
            constraint=models.UniqueConstraint(fields=('NAMA',), name='kesiswaan_kategoriprogramkebaikan_unique'),
        ),
        migrations.AddField(
            model_name='jurnalekskul',
            name='DAFTAR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.daftarjurnalekskul'),
        ),
        migrations.AddField(
            model_name='jurnalekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AddField(
            model_name='jadwalekskul',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='EKSKUL',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='JADWAL_EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.jadwalekskul'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AddField(
            model_name='anggotaekskul',
            name='EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
        migrations.AddField(
            model_name='anggotaekskul',
            name='KELAS_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
        migrations.AddField(
            model_name='anggotaekskul',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
        ),
        migrations.AddField(
            model_name='absensiekskul',
            name='JURNAL_EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.jurnalekskul'),
        ),
        migrations.AddField(
            model_name='absensiekskul',
            name='NIS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddConstraint(
            model_name='programkerjaekskul',
            constraint=models.UniqueConstraint(fields=('PELATIH', 'EKSKUL', 'TAHUN_AJARAN'), name='kesiswaan_programkerjaekskul_unique'),
        ),
        migrations.AddConstraint(
            model_name='programkebaikan',
            constraint=models.UniqueConstraint(fields=('KETERANGAN',), name='kesiswaan_programkebaikan_unique'),
        ),
        migrations.AddConstraint(
            model_name='jadwalekskul',
            constraint=models.UniqueConstraint(fields=('PELATIH', 'HARI', 'TAHUN_AJARAN', 'WAKTU_MULAI', 'WAKTU_BERAKHIR'), name='kesiswaan_jadwalekskul_unique'),
        ),
    ]
