# Generated by Django 4.0 on 2022-03-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0002_alter_anggotaekskul_kelas_siswa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalogekskul',
            name='DOKUMENTASI',
            field=models.ImageField(blank=True, max_length=255, upload_to='KatalogEkskul'),
        ),
    ]
