# Generated by Django 4.0 on 2022-01-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0002_riwayatlaporanpelanggaran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelanggaransiswa',
            old_name='NAMA',
            new_name='DATA_SISWA',
        ),
        migrations.RenameField(
            model_name='pengajuanlaporanpelanggaran',
            old_name='NIS',
            new_name='DATA_SISWA',
        ),
        migrations.RenameField(
            model_name='riwayatlaporanpelanggaran',
            old_name='NIS',
            new_name='DATA_SISWA',
        ),
    ]
