# Generated by Django 4.0 on 2022-02-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0002_nilaiekskul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensiekskul',
            name='KETERANGAN',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], default='Hadir', max_length=255),
        ),
    ]
