# Generated by Django 4.0 on 2022-03-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0002_alter_jurnalbelajar_tanggal_mengajar'),
        ('kesiswaan', '0002_alter_anggotaekskul_kelas_siswa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanekskul',
            name='KELAS_SISWA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
    ]
