# Generated by Django 4.0 on 2022-02-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0078_absensisiswa'),
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
        ('kesiswaan', '0003_rename_nama_pelanggaransiswa_data_siswa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategori Tata Tertib',
                'ordering': ['NAMA'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BUKTI_PROYEK_KEBAIKAN', models.FileField(max_length=255, upload_to='BuktiPelanggaran')),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PoinProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('POIN', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Poin Program Kebaikan',
                'ordering': ['KETERANGAN'],
            },
        ),
        migrations.CreateModel(
            name='ProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('KATEGORI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.kategoriprogramkebaikan')),
            ],
            options={
                'verbose_name_plural': 'Program Kebaikan',
                'ordering': ['KETERANGAN'],
            },
        ),
        migrations.AddConstraint(
            model_name='poinprogramkebaikan',
            constraint=models.UniqueConstraint(fields=('KETERANGAN', 'POIN'), name='kesiswaan_poinprogramkebaikan_unique'),
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='DATA_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='JENIS_PROGRAM_KEBAIKAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.poinpelanggaran'),
        ),
        migrations.AddConstraint(
            model_name='kategoriprogramkebaikan',
            constraint=models.UniqueConstraint(fields=('NAMA',), name='kesiswaan_kategoriprogramkebaikan_unique'),
        ),
        migrations.AddConstraint(
            model_name='programkebaikan',
            constraint=models.UniqueConstraint(fields=('KETERANGAN',), name='kesiswaan_programkebaikan_unique'),
        ),
    ]
