# Generated by Django 4.0 on 2022-03-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0002_alter_jurnalbelajar_tanggal_mengajar'),
        ('kesiswaan', '0003_alter_pengajuanekskul_kelas_siswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggotaekskul',
            name='KELAS_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
        migrations.AlterField(
            model_name='pengajuanekskul',
            name='KELAS_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
    ]
