# Generated by Django 4.0 on 2022-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0004_alter_anggotaekskul_kelas_siswa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jadwalekskul',
            name='kesiswaan_jadwalekskul_unique',
        ),
        migrations.AddConstraint(
            model_name='jadwalekskul',
            constraint=models.UniqueConstraint(fields=('PELATIH', 'HARI', 'TAHUN_AJARAN', 'WAKTU_MULAI', 'WAKTU_BERAKHIR'), name='kesiswaan_jadwalekskul_unique'),
        ),
    ]
