# Generated by Django 4.0 on 2022-02-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0005_alter_kategoriprogramkebaikan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuanprogramkebaikan',
            name='BUKTI_PROYEK_KEBAIKAN',
        ),
        migrations.AddField(
            model_name='pengajuanprogramkebaikan',
            name='BUKTI_PROGRAM_KEBAIKAN',
            field=models.FileField(default=0, max_length=255, upload_to='BuktiProgramKebaikan'),
            preserve_default=False,
        ),
    ]
