# Generated by Django 4.0 on 2022-02-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
        ('kesiswaan', '0006_remove_pengajuanprogramkebaikan_bukti_proyek_kebaikan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatProgramKebaikan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BUKTI_PROGRAM_KEBAIKAN', models.FileField(max_length=255, upload_to='BuktiProgramKebaikan')),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('DATA_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
                ('JENIS_PROGRAM_KEBAIKAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.poinprogramkebaikan')),
            ],
            options={
                'verbose_name_plural': 'Riwayat Laporan Pelanggaran',
            },
        ),
    ]
