# Generated by Django 4.0 on 2022-02-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0007_riwayatprogramkebaikan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riwayatprogramkebaikan',
            options={'verbose_name_plural': 'Riwayat Program Kebaikan'},
        ),
        migrations.RemoveField(
            model_name='pelanggaransiswa',
            name='id',
        ),
        migrations.AddField(
            model_name='pelanggaransiswa',
            name='ID',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
