# Generated by Django 4.0 on 2022-02-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0081_nilairaport'),
        ('dataprofil', '0003_datapelatih'),
        ('kesiswaan', '0008_alter_riwayatprogramkebaikan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarJurnalEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KatalogEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
                ('KATEGORI', models.CharField(choices=[('Wajib', 'Wajib'), ('Pilihan', 'Pilihan'), ('Mandiri', 'Mandiri')], max_length=255)),
                ('DESKRIPSI', models.CharField(max_length=255)),
                ('DOKUMENTASI', models.ImageField(max_length=255, upload_to='KatalogEkskul')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], max_length=255)),
                ('EKSKUL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul')),
                ('KELAS_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa')),
            ],
        ),
        migrations.CreateModel(
            name='JurnalEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PERTEMUAN', models.CharField(max_length=255)),
                ('TANGGAL_MELATIH', models.DateField()),
                ('DESKRIPSI_KEGIATAN', models.TextField()),
                ('FILE_DOKUMENTASI', models.FileField(max_length=255, upload_to='JurnalEkskul')),
                ('DAFTAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.daftarjurnalekskul')),
                ('PELATIH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('HARI', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jum`at', 'Jum`at'), ('Sabtu', 'Sabtu')], max_length=255)),
                ('WAKTU_MULAI', models.TimeField()),
                ('WAKTU_BERAKHIR', models.TimeField()),
                ('EKSKUL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul')),
                ('PELATIH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih')),
                ('SEMESTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester')),
                ('TAHUN_AJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran')),
            ],
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='JADWAL_EKSKUL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.jadwalekskul'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='PELATIH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih'),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.CreateModel(
            name='AnggotaEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EKSKUL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul')),
                ('KELAS_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa')),
            ],
        ),
        migrations.CreateModel(
            name='AbsensiEkskul',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], max_length=255)),
                ('FILE_KETERANGAN', models.FileField(blank=True, max_length=255, upload_to='AbsensiEkskul')),
                ('JURNAL_EKSKUL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.jurnalekskul')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
        ),
    ]
