# Generated by Django 4.0 on 2022-02-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0009_daftarjurnalekskul_katalogekskul_pengajuanekskul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggotaekskul',
            name='STATUS',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='daftarjurnalekskul',
            name='EKSKUL',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.katalogekskul'),
        ),
    ]
