# Generated by Django 4.0 on 2022-02-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0010_anggotaekskul_status_daftarjurnalekskul_ekskul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanekskul',
            name='STATUS_PENGAJUAN',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pengajuan', max_length=255),
        ),
    ]
