# Generated by Django 4.0 on 2022-02-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0013_rename_nama_ekskul_programkerjaekskul_ekskul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramKerjaEkskul',
        ),
    ]
