# Generated by Django 4.0 on 2022-02-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0015_programkerjaekskul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programkerjaekskul',
            old_name='NAMA_EKSKUL',
            new_name='EKSKUL',
        ),
    ]
