# Generated by Django 4.0 on 2022-02-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kustom_autentikasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPelatihUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_PELATIH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datapelatih')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Data Pelatih User',
            },
        ),
    ]
