# Generated by Django 4.0 on 2021-12-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dataprofil', '0013_merge_20211229_1436'),
        ('kustom_autentikasi', '0002_alter_datasiswauser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasiswauser',
            old_name='NISN',
            new_name='DATA_SISWA',
        ),
        migrations.CreateModel(
            name='DataOrangTuaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(blank=True, max_length=255)),
                ('DATA_ORANG_TUA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataorangtua')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Data Orang Tua User',
            },
        ),
        migrations.CreateModel(
            name='DataKaryawanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(blank=True, max_length=255)),
                ('DATA_KARYAWAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Data Karyawan User',
            },
        ),
        migrations.CreateModel(
            name='DataGuruUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(blank=True, max_length=255)),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Data Guru User',
            },
        ),
    ]
