# Generated by Django 4.0 on 2021-12-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0013_merge_20211229_1436'),
        ('kustom_autentikasi', '0003_rename_nisn_datasiswauser_data_siswa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataguruuser',
            name='DATA_GURU',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
    ]
