# Generated by Django 4.0 on 2021-12-31 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kustom_autentikasi', '0005_remove_dataguruuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataguruuser',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
