# Generated by Django 4.0 on 2022-01-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kustom_autentikasi', '0006_alter_dataguruuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakaryawanuser',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='dataorangtuauser',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='datasiswauser',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
