# Generated by Django 4.0 on 2022-03-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0002_alter_dataanakguru_tanggal_lahir_and_more'),
        ('kurikulum', '0002_alter_jurnalbelajar_tanggal_mengajar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapJamGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('DATA_MENGAJAR_GURU', models.ManyToManyField(to='kurikulum.JadwalMengajar')),
            ],
        ),
    ]
