# Generated by Django 4.0 on 2022-03-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekapjamguru',
            name='DATA_MENGAJAR_GURU',
        ),
    ]
