# Generated by Django 4.0 on 2022-04-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0001_initial'),
        ('dataprofil', '0001_initial'),
        ('unit_penjamin_mutu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PembagianTugasGuruTIK',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN_TUGAS', models.TextField(blank=True)),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('DATA_KELAS', models.ManyToManyField(to='kurikulum.OfferingKelas')),
                ('SEMESTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester')),
                ('TAHUN_AJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran')),
            ],
            options={
                'verbose_name_plural': 'Pembagian Tugas Guru BK',
            },
        ),
    ]
