# Generated by Django 4.0 on 2022-04-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0002_pembagiantugasgurutik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pembagiantugasgurutik',
            options={'verbose_name_plural': 'Pembagian Tugas Guru TIK'},
        ),
    ]
