# Generated by Django 4.0 on 2022-03-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0002_alter_jurnalbelajar_tanggal_mengajar'),
        ('unit_penjamin_mutu', '0002_remove_rekapjamguru_data_mengajar_guru'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBukuUPM',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KATEGORI', models.CharField(choices=[('Pembagian Jadwal Mengajar', 'Pembagian Jadwal Mengajar')], default='', max_length=255)),
                ('FILE', models.FileField(blank=True, max_length=255, upload_to='FileBahanBuku')),
                ('TAHUN_AJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran')),
            ],
        ),
        migrations.DeleteModel(
            name='RekapJamGuru',
        ),
    ]
