# Generated by Django 4.0 on 2022-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0003_bahanbukuupm_delete_rekapjamguru'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanbukuupm',
            name='GENERATE',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bahanbukuupm',
            name='START_COL',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bahanbukuupm',
            name='START_ROW',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bahanbukuupm',
            name='TEMPLATE',
            field=models.FileField(blank=True, max_length=255, upload_to='FileBahanBuku'),
        ),
    ]
