# Generated by Django 4.0 on 2022-04-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0004_remove_bahanbukuupm_file_hasil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahanbukuupm',
            name='START_COL',
        ),
        migrations.RemoveField(
            model_name='bahanbukuupm',
            name='START_ROW',
        ),
    ]
