# Generated by Django 4.0 on 2022-03-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0004_bahanbukuupm_generate_bahanbukuupm_start_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanbukuupm',
            name='FILE_HASIL',
            field=models.FileField(blank=True, max_length=255, upload_to='FileBahanBuku'),
        ),
    ]
