# Generated by Django 4.0 on 2022-03-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0003_offeringkelas_kurikulum_offeringkelas_unique'),
        ('unit_penjamin_mutu', '0005_bahanbukuupm_file_hasil'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanbukuupm',
            name='SEMESTER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
            preserve_default=False,
        ),
    ]
