# Generated by Django 4.0 on 2022-04-21 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0001_initial'),
        ('unit_penjamin_mutu', '0006_alter_bahanbukuupm_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembagiantugaspokoktambahantendik',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
    ]
