# Generated by Django 4.0 on 2022-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0006_bahanbukuupm_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahanbukuupm',
            name='START_COL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bahanbukuupm',
            name='START_ROW',
            field=models.IntegerField(default=0),
        ),
    ]
