# Generated by Django 4.0 on 2022-04-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('kurikulum', '0001_initial'),
        ('unit_penjamin_mutu', '0007_pembagiantugaspokoktambahantendik_tahun_ajaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='RincianTugasPokokTambahanTendik',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TUGAS_POKOK', models.TextField()),
                ('TUGAS_TAMBAHAN', models.TextField()),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('TAHUN_AJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran')),
            ],
            options={
                'verbose_name_plural': 'Rincian Tugas Pokok Tenaga Pendidikan',
            },
        ),
    ]
