# Generated by Django 4.0 on 2022-03-17 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0003_offeringkelas_kurikulum_offeringkelas_unique'),
        ('dataprofil', '0002_alter_dataanakguru_tanggal_lahir_and_more'),
        ('unit_penjamin_mutu', '0007_alter_bahanbukuupm_start_col_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bahanbukuupm',
            options={'verbose_name_plural': 'Bahan Buku UPM'},
        ),
        migrations.AlterField(
            model_name='bahanbukuupm',
            name='KATEGORI',
            field=models.CharField(choices=[('Pembagian Jadwal Mengajar', 'Pembagian Jadwal Mengajar'), ('Rekapitulasi Jumlah Jam Mengajar', 'Rekapitulasi Jumlah Jam Mengajar')], default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PembagianTugasGuruBK',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN_TUGAS', models.TextField()),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('DATA_KELAS', models.ManyToManyField(to='kurikulum.OfferingKelas')),
            ],
        ),
    ]
