# Generated by Django 4.0 on 2022-03-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0003_offeringkelas_kurikulum_offeringkelas_unique'),
        ('unit_penjamin_mutu', '0008_alter_bahanbukuupm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembagiantugasgurubk',
            name='SEMESTER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembagiantugasgurubk',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pembagiantugasgurubk',
            name='KETERANGAN_TUGAS',
            field=models.TextField(blank=True),
        ),
    ]
