# Generated by Django 4.0 on 2022-03-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0009_pembagiantugasgurubk_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahanbukuupm',
            name='KATEGORI',
            field=models.CharField(choices=[('Pembagian Jadwal Mengajar', 'Pembagian Jadwal Mengajar'), ('Rekapitulasi Jumlah Jam Mengajar', 'Rekapitulasi Jumlah Jam Mengajar'), ('Pembagian Tugas BK Semester', 'Pembagian Tugas BK Semester')], default='', max_length=255),
        ),
    ]
