# Generated by Django 4.0 on 2022-04-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('unit_penjamin_mutu', '0009_jenisbidang_alter_bahanbukuupm_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jenisbidang',
            options={'verbose_name_plural': 'Jenis Bidang'},
        ),
        migrations.CreateModel(
            name='TugasTambahanKepanitiaanTendik',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TUGAS', models.CharField(max_length=255)),
                ('BIDANG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_penjamin_mutu.jenisbidang')),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
            ],
            options={
                'verbose_name_plural': 'Pembagian Tugas Tambahan dan Kepanitiaan Tendik',
            },
        ),
    ]
