# Generated by Django 4.0 on 2022-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0010_alter_jenisbidang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugastambahankepanitiaantendik',
            name='SUB_BIDANG',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
