# Generated by Django 4.0 on 2022-04-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0001_initial'),
        ('unit_penjamin_mutu', '0011_tugastambahankepanitiaantendik_sub_bidang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugastambahankepanitiaantendik',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bahanbukuupm',
            name='KATEGORI',
            field=models.CharField(choices=[('Pembagian Jadwal Mengajar', 'Pembagian Jadwal Mengajar'), ('Rekapitulasi Jumlah Jam Mengajar', 'Rekapitulasi Jumlah Jam Mengajar'), ('Pembagian Tugas BK Semester', 'Pembagian Tugas BK Semester'), ('Pembagian Tugas TIK Semester', 'Pembagian Tugas TIK Semester'), ('Pembagian Tugas Pokok dan Tambahan Tenaga Kependidikan', 'Pembagian Tugas Pokok dan Tambahan Tenaga Kependidikan'), ('Rincian Tugas Pokok dan Tambahan Tenaga Kependidikan', 'Rincian Tugas Pokok dan Tambahan Tenaga Kependidikan'), ('Lampiran Tugas Tambahan dan Kepanitiaan', 'Lampiran Tugas Tambahan dan Kepanitiaan')], default='', max_length=255),
        ),
    ]
