# Generated by Django 4.0 on 2022-03-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_penjamin_mutu', '0012_alter_bahanbukuupm_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembagiantugaspokoktambahantendik',
            name='TUGAS_TAMBAHAN',
            field=models.CharField(max_length=255),
        ),
    ]
