services:
  web:
    build: ./adistetsa
    command: gunicorn adistetsa.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - static_volume:/home/adistetsa/web/staticfiles
      - media_volume:/home/adistetsa/web/savedfiles
      - ./adistetsa:/usr/src/adistetsa
    expose:
      - 8000
    env_file:
      - ./.env.dev
    restart: always

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adistetsa
      - POSTGRES_PASSWORD=merdeka123
      - POSTGRES_DB=adistetsa_db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/adistetsa/web/staticfiles
      - media_volume:/home/adistetsa/web/savedfiles
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: