services:
  web:
    build:
      context: ./adistetsa
      dockerfile: Dockerfile.prod
    command: gunicorn adistetsa.wsgi:application --bind 0.0.0.0:8000 --workers=3 --threads=3
    volumes:
      - static_volume:/home/adistetsa/web/staticfiles
      - media_volume:/home/adistetsa/web/savedfiles
      - ./adistetsa:/home/adistetsa/web
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/adistetsa/web/staticfiles
      - media_volume:/home/adistetsa/web/savedfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: