services:
  web:
    build: ./adistetsa
    command: gunicorn adistetsa.wsgi:application --bind 0.0.0.0:8000 --workers=3 --threads=3 --reload
    volumes:
      - ./adistetsa:/usr/src/adistetsa
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    restart: always

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adistetsa
      - POSTGRES_PASSWORD=merdeka123
      - POSTGRES_DB=adistetsa_db

volumes:
  postgres_data: