# POST http://localhost:8000/login/
# Content-Type: application/json

# {
#     "username": "lauren_ramos_1997",
#     "password": "merdeka123"
# }

GET http://localhost:8000/kurikulum/jurnal_belajar_mengajar?TAHUN_AJARAN=1&HARI=Senin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQ2NTQ2OTM2LCJpYXQiOjE2NDUyNTA5MzYsImp0aSI6IjQ5YTUwZjJiZTg4NjQwOTA5OTJkYmFjNzUzM2NhZDYyIiwidXNlcl9pZCI6Mjh9.5qW7DK8V-tzp-2KnbcMX2JYMhEtqlsiGahFm6eUizds
Content-Type: application/json

# {
#     "KETERANGAN": "Sakit"
# }

# {
#     "PENGGUNA": "Afdhal",
#     "NO_HP": "081132324040",
#     "KEGIATAN": "Lomba Basket",
#     "RUANGAN": 1,
#     "TANGGAL_PEMAKAIAN": "2022-02-20",
#     "TANGGAL_BERAKHIR": "2022-02-27",
#     "JAM_PENGGUNAAN": "10:00",
#     "JAM_BERAKHIR": "13:00",
#     "JENIS_PEMINJAMAN": "Jangka Pendek",
#     "KETERANGAN": "Dibutuhkan pulpen untuk menulis pada acara baca tulis"
# }



# POST http://localhost:8000/perpustakaan/pengajuan_peminjaman_siswa
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQ2MzQ0ODQ2LCJpYXQiOjE2NDUwNDg4NDYsImp0aSI6IjgzNWQxMjU3YzgwYzRiOGY4NjY2MWZlMDQ1N2YyYjNiIiwidXNlcl9pZCI6OX0.YEsn8CQZu4Cna-ghKMyaIuUSYk-9ToxlXozfoN38kPc
# Content-Type: application/json

# {
#     "BUKU": [14, 15],
#     "TANGGAL_PENGAJUAN": "2022-09-09",
#     "STATUS_PENGAJUAN": "Pengajuan",
#     "JANGKA_PEMINJAMAN": "Jangka Pendek"
# }