# Generated by Django 4.0 on 2022-02-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariPenggunaan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('HARI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPenggunaanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam'), ('Ditolak', 'Ditolak')], default='Selesai Dipinjam', max_length=255)),
                ('HARI', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jum`at', 'Jum`at'), ('Sabtu', 'Sabtu')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JamPenggunaan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JAM_KE', models.IntegerField()),
                ('PUKUL', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JenisRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KATEGORI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JenisSarana',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KATEGORI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
                ('STATUS', models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak')], default='Sudah Dikembalikan', max_length=255)),
                ('JENIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jenissarana')),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
                ('STATUS', models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak')], default='Sudah Dikembalikan', max_length=255)),
                ('JENIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jenisruangan')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPeminjamanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PENGGUNA', models.CharField(max_length=255)),
                ('NO_HP', models.PositiveBigIntegerField()),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_SELESAI', models.DateField()),
                ('JENIS_PEMINJAMAN', models.CharField(choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('STATUS', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('KETERANGAN', models.TextField(max_length=255)),
                ('RUANGAN', models.ManyToManyField(to='sarana_prasarana.JadwalPenggunaanRuangan')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPeminjamanBarang',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_PEMINJAM', models.CharField(default='', max_length=255)),
                ('NO_TELEPON', models.CharField(default='', max_length=255)),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('TANGGAL_PENGEMBALIAN', models.DateField()),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('STATUS_PEMINJAMAN', models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak')], default='Sedang Dipinjam', max_length=255)),
                ('TANDA_TANGAN', models.FileField(blank=True, max_length=255, upload_to='BuktiPelanggaran')),
                ('ALAT', models.ManyToManyField(to='sarana_prasarana.Sarana')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanPeminjamanRuanganPendek',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('KETERANGAN', models.TextField(max_length=255)),
                ('DATA_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
                ('HARI_PENGGUNAAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.haripenggunaan')),
                ('RUANGAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.ruangan')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanPeminjamanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PENGGUNA', models.CharField(max_length=255)),
                ('NO_HP', models.PositiveBigIntegerField()),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('STATUS', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('JENIS_PEMINJAMAN', models.CharField(choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('KETERANGAN', models.TextField(max_length=255)),
                ('RUANGAN', models.ManyToManyField(to='sarana_prasarana.JadwalPenggunaanRuangan')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanPeminjamanBarang',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_PEMINJAM', models.CharField(default='', max_length=255)),
                ('NO_TELEPON', models.CharField(default='', max_length=255)),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('TANGGAL_PENGEMBALIAN', models.DateField(blank=True, null=True)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pengajuan', max_length=255)),
                ('TANDA_TANGAN', models.FileField(blank=True, max_length=255, upload_to='BuktiPelanggaran')),
                ('ALAT', models.ManyToManyField(to='sarana_prasarana.Sarana')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='jadwalpenggunaanruangan',
            name='JAM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jampenggunaan'),
        ),
        migrations.AddField(
            model_name='jadwalpenggunaanruangan',
            name='RUANGAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.ruangan'),
        ),
        migrations.AddField(
            model_name='haripenggunaan',
            name='JAM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jampenggunaan'),
        ),
    ]
