# Generated by Django 4.0 on 2022-02-18 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KATEGORI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JenisSarana',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KATEGORI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
                ('STATUS', models.CharField(choices=[('Tenggat', 'Tenggat'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sudah Dikembalikan', max_length=255)),
                ('JENIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jenissarana')),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
                ('STATUS', models.CharField(choices=[('Tenggat', 'Tenggat'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sudah Dikembalikan', max_length=255)),
                ('JENIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jenisruangan')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPeminjamanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PENGGUNA', models.CharField(max_length=255)),
                ('NO_HP', models.CharField(max_length=255)),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField(default=django.utils.timezone.now)),
                ('TANGGAL_PEMAKAIAN', models.DateField(default=django.utils.timezone.now)),
                ('TANGGAL_BERAKHIR', models.DateField(default=django.utils.timezone.now)),
                ('JAM_PENGGUNAAN', models.TimeField(default=django.utils.timezone.now)),
                ('JAM_BERAKHIR', models.TimeField(default=django.utils.timezone.now)),
                ('STATUS', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('JENIS_PEMINJAMAN', models.CharField(choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('KETERANGAN', models.TextField(max_length=255)),
                ('TANDA_TANGAN', models.FileField(blank=True, max_length=255, upload_to='PeminjamanRuangan')),
                ('RUANGAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.ruangan')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPeminjamanBarang',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_PEMINJAM', models.CharField(default='', max_length=255)),
                ('NO_TELEPON', models.CharField(default='', max_length=255)),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('TANGGAL_PENGEMBALIAN', models.DateField()),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('STATUS_PEMINJAMAN', models.CharField(choices=[('Tenggat', 'Tenggat'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sedang Dipinjam', max_length=255)),
                ('TANDA_TANGAN', models.FileField(blank=True, max_length=255, upload_to='PeminjamanBarang')),
                ('ALAT', models.ManyToManyField(to='sarana_prasarana.Sarana')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanPeminjamanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PENGGUNA', models.CharField(max_length=255)),
                ('NO_HP', models.CharField(max_length=255)),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField(default=django.utils.timezone.now)),
                ('TANGGAL_PEMAKAIAN', models.DateField(default=django.utils.timezone.now)),
                ('TANGGAL_BERAKHIR', models.DateField(default=django.utils.timezone.now)),
                ('JAM_PENGGUNAAN', models.TimeField(default=django.utils.timezone.now)),
                ('JAM_BERAKHIR', models.TimeField(default=django.utils.timezone.now)),
                ('STATUS', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('JENIS_PEMINJAMAN', models.CharField(choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('KETERANGAN', models.TextField(max_length=255)),
                ('TANDA_TANGAN', models.FileField(blank=True, max_length=255, upload_to='PeminjamanRuangan')),
                ('RUANGAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.ruangan')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanPeminjamanBarang',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_PEMINJAM', models.CharField(default='', max_length=255)),
                ('NO_TELEPON', models.CharField(default='', max_length=255)),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('TANGGAL_PENGEMBALIAN', models.DateField(blank=True, null=True)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pengajuan', max_length=255)),
                ('TANDA_TANGAN', models.FileField(blank=True, max_length=255, upload_to='PeminjamanBarang')),
                ('ALAT', models.ManyToManyField(to='sarana_prasarana.Sarana')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
