# Generated by Django 4.0 on 2022-02-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
