# Generated by Django 4.0 on 2022-03-03 07:51

import adistetsa.custom_function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisruangan',
            name='KATEGORI',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='jenissarana',
            name='KATEGORI',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanruangan',
            name='NO_HP',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.validasi_integer]),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanruangan',
            name='PENGGUNA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.paksa_huruf_besar]),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='NAMA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='NAMA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
    ]
