# Generated by Django 4.0 on 2022-02-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='DATA_SISWA',
        ),
        migrations.AddField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='NO_HP',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='PENGGUNA',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jampenggunaan',
            name='PUKUL',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='JadwalPenggunaanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Diajukan'), ('Selesai Dipinjam', 'Selesai Dipinjam')], default='Diajukan', max_length=255)),
                ('JAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jampenggunaan')),
                ('RUANGAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.ruangan')),
            ],
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='RUANGAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.jadwalpenggunaanruangan'),
        ),
    ]
