# Generated by Django 4.0 on 2022-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Hilang', 'Hilang'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
