# Generated by Django 4.0 on 2022-02-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0002_remove_pengajuanpeminjamanruanganpendek_data_siswa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='HARI_PENGGUNAAN',
        ),
    ]
