# Generated by Django 4.0 on 2022-02-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0002_remove_pengajuanpeminjamanruangan_tanggal_penggunaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
