# Generated by Django 4.0 on 2022-02-17 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0002_remove_pengajuanpeminjamanruangan_tanggal_pengajuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanpeminjamanruangan',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Ditolak', 'Ditolak')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Ditolak', 'Ditolak')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Ditolak', 'Ditolak')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
