# Generated by Django 4.0 on 2022-02-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0004_alter_riwayatpeminjamanbarang_status_peminjaman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
