# Generated by Django 4.0 on 2022-02-17 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0004_alter_riwayatpeminjamanbarang_status_peminjaman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatpeminjamanruangan',
            name='TANGGAL_SELESAI',
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanruangan',
            name='JAM_BERAKHIR',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanruangan',
            name='JAM_PENGGUNAAN',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanruangan',
            name='TANGGAL_BERAKHIR',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanruangan',
            name='TANGGAL_PEMAKAIAN',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanruangan',
            name='NO_HP',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='riwayatpeminjamanruangan',
            name='RUANGAN',
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanruangan',
            name='RUANGAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sarana_prasarana.ruangan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanruangan',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
