# Generated by Django 4.0 on 2022-02-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0005_alter_riwayatpeminjamanbarang_status_peminjaman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalpenggunaanruangan',
            name='JAM',
        ),
        migrations.RemoveField(
            model_name='jadwalpenggunaanruangan',
            name='RUANGAN',
        ),
        migrations.RemoveField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='DATA_SISWA',
        ),
        migrations.RemoveField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='HARI_PENGGUNAAN',
        ),
        migrations.RemoveField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='RUANGAN',
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.DeleteModel(
            name='HariPenggunaan',
        ),
        migrations.DeleteModel(
            name='JadwalPenggunaanRuangan',
        ),
        migrations.DeleteModel(
            name='JamPenggunaan',
        ),
        migrations.DeleteModel(
            name='PengajuanPeminjamanRuanganPendek',
        ),
    ]
