# Generated by Django 4.0 on 2022-02-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0005_alter_pengajuanpeminjamanbarang_tanggal_pengajuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanpeminjamanbarang',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanruangan',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Pengajuan', 'Pengajuan')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Pengajuan', 'Pengajuan')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Pengajuan', 'Pengajuan')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
