# Generated by Django 4.0 on 2022-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0005_remove_pengajuanpeminjamanruanganpendek_ruangan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPeminjamanRuanganPendek',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PENGGUNA', models.CharField(max_length=255)),
                ('NO_HP', models.PositiveBigIntegerField()),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('KETERANGAN', models.TextField(max_length=255)),
                ('RUANGAN', models.ManyToManyField(to='sarana_prasarana.JadwalPenggunaanRuangan')),
            ],
        ),
    ]
