# Generated by Django 4.0 on 2022-02-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sarana_prasarana', '0005_pengajuanpeminjamanbarang_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpeminjamanbarang',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
