# Generated by Django 4.0 on 2022-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0005_remove_riwayatpeminjamanruangan_tanggal_selesai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanpeminjamanruangan',
            name='TANDA_TANGAN',
            field=models.FileField(blank=True, max_length=255, upload_to='PeminjamanRuangan'),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanruangan',
            name='TANDA_TANGAN',
            field=models.FileField(blank=True, max_length=255, upload_to='PeminjamanRuangan'),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanbarang',
            name='TANDA_TANGAN',
            field=models.FileField(blank=True, max_length=255, upload_to='PeminjamanBarang'),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='TANDA_TANGAN',
            field=models.FileField(blank=True, max_length=255, upload_to='PeminjamanBarang'),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
