# Generated by Django 4.0 on 2022-02-19 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0006_alter_pengajuanpeminjamanbarang_tanggal_pengajuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanpeminjamanbarang',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanruangan',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanruangan',
            name='JAM_BERAKHIR',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanruangan',
            name='JAM_PENGGUNAAN',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanruangan',
            name='TANGGAL_BERAKHIR',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanruangan',
            name='TANGGAL_PEMAKAIAN',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanruangan',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat'), ('Hilang', 'Hilang'), ('Pengajuan', 'Pengajuan')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
