# Generated by Django 4.0 on 2022-02-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0006_riwayatpeminjamanruanganpendek'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='STATUS',
            field=models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Diajukan'), ('Selesai Dipinjam', 'Selesai Dipinjam')], default='Diajukan', max_length=255),
        ),
    ]
