# Generated by Django 4.0 on 2022-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0007_pengajuanpeminjamanruanganpendek_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPeminjamanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PENGGUNA', models.CharField(max_length=255)),
                ('NO_HP', models.PositiveBigIntegerField()),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('JENIS_PEMINJAMAN', models.CharField(choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('KETERANGAN', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='jadwalpenggunaanruangan',
            name='STATUS',
            field=models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam')], default='Selesai Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanruanganpendek',
            name='STATUS',
            field=models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam')], default='Diajukan', max_length=255),
        ),
        migrations.DeleteModel(
            name='RiwayatPeminjamanRuanganPendek',
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanruangan',
            name='RUANGAN',
            field=models.ManyToManyField(to='sarana_prasarana.JadwalPenggunaanRuangan'),
        ),
    ]
