# Generated by Django 4.0 on 2022-02-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0007_alter_riwayatpeminjamanbarang_status_peminjaman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuanpeminjamanbarang',
            name='DATA_SISWA',
        ),
        migrations.RemoveField(
            model_name='riwayatpeminjamanbarang',
            name='DATA_SISWA',
        ),
        migrations.AddField(
            model_name='pengajuanpeminjamanbarang',
            name='NAMA_PEMINJAM',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pengajuanpeminjamanbarang',
            name='NO_TELEPON',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanbarang',
            name='NAMA_PEMINJAM',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamanbarang',
            name='NO_TELEPON',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Ditolak', 'Ditolak'), ('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Ditolak', 'Ditolak'), ('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Pengajuan', 'Pengajuan')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
