# Generated by Django 4.0 on 2022-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0007_riwayatpeminjamanruangan_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='STATUS',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanbarang',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='sarana',
            name='STATUS',
            field=models.CharField(choices=[('Hilang', 'Hilang'), ('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sudah Dikembalikan', max_length=255),
        ),
    ]
