# Generated by Django 4.0 on 2022-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_prasarana', '0008_riwayatpeminjamanruangan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanPeminjamanRuangan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PENGGUNA', models.CharField(max_length=255)),
                ('NO_HP', models.PositiveBigIntegerField()),
                ('KEGIATAN', models.CharField(max_length=255)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('TANGGAL_PENGGUNAAN', models.DateField()),
                ('STATUS', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Selesai Dipinjam', 'Selesai Dipinjam')], default='Diajukan', max_length=255)),
                ('JENIS_PEMINJAMAN', models.CharField(choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('KETERANGAN', models.TextField(max_length=255)),
                ('RUANGAN', models.ManyToManyField(to='sarana_prasarana.JadwalPenggunaanRuangan')),
            ],
        ),
        migrations.DeleteModel(
            name='PengajuanPeminjamanRuanganPendek',
        ),
    ]
