# Generated by Django 4.0 on 2022-03-14 07:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurikulum', '0002_alter_jurnalbelajar_tanggal_mengajar'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAlumni',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_SISWA', models.CharField(max_length=255)),
                ('KELAS', models.CharField(max_length=255)),
                ('NISN', models.CharField(max_length=255)),
                ('NIS', models.CharField(max_length=255)),
                ('TAHUN_AJARAN', models.CharField(max_length=255)),
                ('NAMA_PT', models.CharField(blank=True, max_length=255)),
                ('PROGRAM_STUDI', models.CharField(blank=True, max_length=255)),
                ('MEDIA_SOSIAL', models.CharField(blank=True, max_length=255)),
                ('EMAIL', models.EmailField(blank=True, max_length=255)),
                ('ALAMAT', models.CharField(blank=True, max_length=255)),
                ('TEMPAT_BEKERJA', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Data Alumni',
            },
        ),
        migrations.CreateModel(
            name='KatalogKonselor',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KOMPETENSI', models.CharField(blank=True, max_length=255)),
                ('ALUMNUS', models.CharField(blank=True, max_length=255)),
                ('WHATSAPP', models.URLField(blank=True, max_length=255)),
                ('CONFERENCE', models.URLField(blank=True, max_length=255)),
                ('STATUS', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=255)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Katalog Konselor',
            },
        ),
        migrations.CreateModel(
            name='RiwayatKonsultasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_KONSULTASI', models.DateField(default=datetime.date.today, max_length=255)),
                ('JAM', models.TimeField(max_length=255)),
                ('JENIS_MASALAH', models.CharField(choices=[('Karier', 'Karier'), ('Pribadi', 'Pribadi'), ('Sosial', 'Sosial'), ('Belajar', 'Belajar')], max_length=255)),
                ('RATING', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('STATUS', models.CharField(choices=[('Sedang Konsultasi', 'Sedang Konsultasi'), ('Selesai Konsultasi', 'Selesai Konsultasi'), ('Diajukan', 'Diajukan'), ('Dibatalkan', 'Dibatalkan'), ('Ditolak', 'Ditolak')], default='Sedang Konsultasi', max_length=255)),
                ('KONSELOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bimbingan_konseling.katalogkonselor')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Riwayat Konsultasi',
            },
        ),
        migrations.CreateModel(
            name='PengajuanKonsultasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_KONSULTASI', models.DateField(default=datetime.date.today, max_length=255)),
                ('JAM', models.TimeField(max_length=255)),
                ('JENIS_MASALAH', models.CharField(choices=[('Karier', 'Karier'), ('Pribadi', 'Pribadi'), ('Sosial', 'Sosial'), ('Belajar', 'Belajar')], max_length=255)),
                ('STATUS', models.CharField(choices=[('Sedang Konsultasi', 'Sedang Konsultasi'), ('Selesai Konsultasi', 'Selesai Konsultasi'), ('Diajukan', 'Diajukan'), ('Dibatalkan', 'Dibatalkan'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('KONSELOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bimbingan_konseling.katalogkonselor')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Pengajuan Konsultasi',
            },
        ),
        migrations.CreateModel(
            name='PeminatanLintasMinat',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KATEGORI', models.CharField(choices=[('Angket Peminatan', 'Angket Peminatan'), ('Angket Lintas Minat', 'Angket Lintas Minat'), ('Angket Data Diri', 'Angket Data Diri')], max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='Dokumen_Peminatan_Lintas_Minat')),
                ('KELAS_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa')),
            ],
            options={
                'verbose_name_plural': 'Peminatan dan Lintas Minat',
            },
        ),
    ]
