# Generated by Django 4.0 on 2022-03-14 08:53

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bimbingan_konseling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_KONSULTASI', models.DateField(default=datetime.date.today, max_length=255)),
                ('JAM', models.TimeField(max_length=255)),
                ('JENIS_MASALAH', models.CharField(choices=[('Karier', 'Karier'), ('Pribadi', 'Pribadi'), ('Sosial', 'Sosial'), ('Belajar', 'Belajar')], max_length=255)),
                ('RATING', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('STATUS', models.CharField(choices=[('Sedang Konsultasi', 'Sedang Konsultasi'), ('Selesai Konsultasi', 'Selesai Konsultasi'), ('Diajukan', 'Diajukan'), ('Telah Mengisi Rating', 'Telah Mengisi Rating'), ('Ditolak', 'Ditolak')], default='Sedang Konsultasi', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Konsultasi',
            },
        ),
        migrations.RemoveField(
            model_name='riwayatkonsultasi',
            name='KONSELOR',
        ),
        migrations.RemoveField(
            model_name='riwayatkonsultasi',
            name='USER',
        ),
        migrations.AddField(
            model_name='katalogkonselor',
            name='FOTO',
            field=models.ImageField(blank=True, max_length=255, upload_to='Foto_Profil_BK'),
        ),
        migrations.DeleteModel(
            name='PengajuanKonsultasi',
        ),
        migrations.DeleteModel(
            name='RiwayatKonsultasi',
        ),
        migrations.AddField(
            model_name='konsultasi',
            name='KONSELOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bimbingan_konseling.katalogkonselor'),
        ),
        migrations.AddField(
            model_name='konsultasi',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
