# Generated by Django 4.0 on 2022-03-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurikulum', '0001_initial'),
        ('bimbingan_konseling', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminatanlintasminat',
            name='KELAS_SISWA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
        ),
        migrations.AddField(
            model_name='konsultasi',
            name='KONSELOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bimbingan_konseling.katalogkonselor'),
        ),
        migrations.AddField(
            model_name='konsultasi',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='katalogkonselor',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddConstraint(
            model_name='peminatanlintasminat',
            constraint=models.UniqueConstraint(fields=('KELAS_SISWA', 'KATEGORI'), name='bimbingan_konseling_peminatanlintasminat_unique'),
        ),
    ]
