# Generated by Django 4.0 on 2022-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan_konseling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalogkonselor',
            name='NAMA',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
