# Generated by Django 4.0 on 2022-03-14 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan_konseling', '0002_konsultasi_remove_riwayatkonsultasi_konselor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsultasi',
            name='RATING',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
