# Generated by Django 4.0 on 2022-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan_konseling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminatanlintasminat',
            name='FILE_ANGKET',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='Dokumen_Peminatan_Lintas_Minat'),
        ),
    ]
