# Generated by Django 4.0 on 2022-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan_konseling', '0003_peminatanlintasminat_file_angket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminatanlintasminat',
            name='FILE',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='Dokumen_Peminatan_Lintas_Minat'),
        ),
    ]
