# Generated by Django 4.0 on 2022-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan_konseling', '0003_alter_konsultasi_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsultasi',
            name='STATUS',
            field=models.CharField(choices=[('Dijadwalkan', 'Dijadwalkan'), ('Selesai', 'Selesai'), ('Diajukan', 'Diajukan'), ('Telah Mengisi Feedback', 'Telah Mengisi Feedback'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255),
        ),
    ]
