# Generated by Django 4.0 on 2022-01-06 07:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulanMinggu',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_BULAN', models.CharField(max_length=255)),
                ('JUMLAH_MINGGU', models.IntegerField()),
                ('TAHUN', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='DeskripsiTataTertib',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('POIN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JadwalHarian',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('HARI', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jum`at', 'Jum`at'), ('Sabtu', 'Sabtu')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KegiatanPekanTidakEfektif',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('URAIAN_KEGIATAN', models.CharField(max_length=255)),
                ('JUMLAH_MINGGU', models.IntegerField()),
                ('KETERANGAN', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('TAHUN_AJARAN_AWAL', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('TAHUN_AJARAN_AKHIR', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('TINGKATAN', models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=255)),
                ('KODE_KELAS', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KTSP',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAHUN_AJARAN_AWAL', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('TAHUN_AJARAN_AKHIR', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('NAMA_FILE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('KODE', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mengajar',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ID_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('MATA_PELAJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='WaktuPelajaran',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('WAKTU_MULAI', models.TimeField()),
                ('WAKTU_BERAKHIR', models.TimeField()),
                ('JAM_KE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TataTertib',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DAFTAR', models.ManyToManyField(to='kurikulum.DeskripsiTataTertib')),
            ],
        ),
        migrations.CreateModel(
            name='SilabusRPB',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAHUN_AJARAN_AWAL', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('TAHUN_AJARAN_AKHIR', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('NAMA_FILE', models.CharField(max_length=255)),
                ('KELAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelas')),
                ('MATA_PELAJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.mengajar')),
                ('MATA_PELAJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matapelajaran')),
                ('WAKTU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.waktupelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='KelasSiswa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KELAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelas')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='JurnalBelajar',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_MENGAJAR', models.DateField()),
                ('DESKRIPSI_MATERI', models.CharField(max_length=1020)),
                ('FILE_DOKUMENTASI', models.CharField(max_length=255)),
                ('KELAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelas')),
                ('PELAJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SEMESTER', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=255)),
                ('JADWAL_HARIAN', models.ManyToManyField(to='kurikulum.JadwalHarian')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPekanTidakEfektif',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KEGIATAN', models.ManyToManyField(to='kurikulum.KegiatanPekanTidakEfektif')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPekanEfektifSemester',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JUMLAH', models.IntegerField()),
                ('BANYAK_MINGGU', models.ManyToManyField(to='kurikulum.BulanMinggu')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPekanAktif',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SEMESTER', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=255)),
                ('PEKAN_AKTIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.jadwalpekanefektifsemester')),
                ('PEKAN_TIDAK_EFEKTIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.jadwalpekantidakefektif')),
            ],
        ),
        migrations.AddField(
            model_name='jadwalharian',
            name='KELAS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelas'),
        ),
        migrations.AddField(
            model_name='jadwalharian',
            name='PELAJARAN',
            field=models.ManyToManyField(to='kurikulum.Pelajaran'),
        ),
        migrations.CreateModel(
            name='AbsensiSiswa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('KETERANGAN', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], max_length=255)),
                ('FILE_DOKUMEN', models.CharField(blank=True, max_length=255)),
                ('KELAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelas')),
            ],
        ),
    ]
