# Generated by Django 4.0 on 2022-03-04 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalbelajar',
            name='TANGGAL_MENGAJAR',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
