# Generated by Django 4.0 on 2022-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0002_alter_ktsp_nama_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktsp',
            name='NAMA_FILE',
            field=models.FileField(max_length=255, upload_to='Dokumen_KTSP'),
        ),
    ]
