# Generated by Django 4.0 on 2022-01-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0003_alter_ktsp_nama_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensisiswa',
            name='FILE_DOKUMEN',
            field=models.FileField(max_length=255, upload_to='Dokumen_AbsensiSiswa'),
        ),
        migrations.AlterField(
            model_name='jurnalbelajar',
            name='FILE_DOKUMENTASI',
            field=models.FileField(max_length=255, upload_to='JurnalBelajar'),
        ),
        migrations.AlterField(
            model_name='silabusrpb',
            name='NAMA_FILE',
            field=models.FileField(max_length=255, upload_to='Dokumen_SilabusRPB'),
        ),
    ]
