# Generated by Django 4.0 on 2022-03-03 07:51

import adistetsa.custom_function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0003_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='NAMA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.paksa_huruf_besar]),
        ),
        migrations.AlterField(
            model_name='kategoritatatertib',
            name='NAMA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='NAMA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat], verbose_name='MATA PELAJARAN'),
        ),
        migrations.AlterField(
            model_name='namaofferingkelas',
            name='NAMA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.paksa_huruf_besar]),
        ),
    ]
