# Generated by Django 4.0 on 2022-01-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0004_alter_absensisiswa_file_dokumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
