# Generated by Django 4.0 on 2022-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0005_alter_kelas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskripsitatatertib',
            name='POIN',
            field=models.PositiveIntegerField(),
        ),
    ]
