# Generated by Django 4.0 on 2022-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0006_alter_deskripsitatatertib_poin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskripsitatatertib',
            name='POIN',
            field=models.IntegerField(),
        ),
    ]
