# Generated by Django 4.0 on 2022-01-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0008_alter_deskripsitatatertib_poin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='KODE_KELAS',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
