# Generated by Django 4.0 on 2022-01-07 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0009_alter_kelas_kode_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAHUN_AJARAN_AWAL', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('TAHUN_AJARAN_AKHIR', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.RemoveField(
            model_name='ktsp',
            name='TAHUN_AJARAN_AKHIR',
        ),
        migrations.RemoveField(
            model_name='ktsp',
            name='TAHUN_AJARAN_AWAL',
        ),
        migrations.AlterField(
            model_name='kelas',
            name='KODE_KELAS',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='ktsp',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
    ]
