# Generated by Django 4.0 on 2022-01-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0010_tahunajaran_remove_ktsp_tahun_ajaran_akhir_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ktsp',
            old_name='TAHUN_AJARAN',
            new_name='TAHUN_AJARANA',
        ),
    ]
