# Generated by Django 4.0 on 2022-01-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0011_rename_tahun_ajaran_ktsp_tahun_ajarana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ktsp',
            old_name='TAHUN_AJARANA',
            new_name='TAHUN_AJARAN',
        ),
    ]
