# Generated by Django 4.0 on 2022-01-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0012_rename_tahun_ajarana_ktsp_tahun_ajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silabusrpb',
            name='TAHUN_AJARAN_AKHIR',
        ),
        migrations.RemoveField(
            model_name='silabusrpb',
            name='TAHUN_AJARAN_AWAL',
        ),
        migrations.AddField(
            model_name='silabusrpb',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
    ]
