# Generated by Django 4.0 on 2022-01-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0013_remove_silabusrpb_tahun_ajaran_akhir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='TAHUN_AJARAN_AKHIR',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='TAHUN_AJARAN_AWAL',
        ),
        migrations.AddField(
            model_name='kelas',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
    ]
