# Generated by Django 4.0 on 2022-01-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0014_remove_kelas_tahun_ajaran_akhir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalbelajar',
            name='SEMESTER',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.jadwalpelajaran'),
            preserve_default=False,
        ),
    ]
