# Generated by Django 4.0 on 2022-01-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0015_jurnalbelajar_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KE', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='jadwalpekanaktif',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AlterField(
            model_name='jadwalpelajaran',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
        migrations.AlterField(
            model_name='jurnalbelajar',
            name='SEMESTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
    ]
