# Generated by Django 4.0 on 2022-01-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0016_datasemester_alter_jadwalpekanaktif_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasemester',
            name='NAMA',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
