# Generated by Django 4.0 on 2022-01-08 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0018_alter_matapelajaran_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='silabusrpb',
            name='SEMESTER',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kelas',
            name='KODE_KELAS',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='KELAS'),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='NAMA',
            field=models.CharField(max_length=255, verbose_name='MATA PELAJARAN'),
        ),
    ]
