# Generated by Django 4.0 on 2022-01-08 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0019_silabusrpb_semester_alter_kelas_kode_kelas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabusrpb',
            name='SEMESTER',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester'),
        ),
    ]
