# Generated by Django 4.0 on 2022-01-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0020_alter_silabusrpb_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silabusrpb',
            name='SEMESTER',
        ),
    ]
