# Generated by Django 4.0 on 2022-01-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0022_silabusrpb_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasemester',
            name='KE',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=255, verbose_name='SEMESTER'),
        ),
    ]
