# Generated by Django 4.0 on 2022-01-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0023_alter_datasemester_ke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasemester',
            name='KE',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=255),
        ),
        migrations.AlterField(
            model_name='datasemester',
            name='NAMA',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEMESTER'),
        ),
    ]
