# Generated by Django 4.0 on 2022-01-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0024_alter_datasemester_ke_alter_datasemester_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensisiswa',
            name='FILE_DOKUMEN',
            field=models.FileField(blank=True, max_length=255, upload_to='Dokumen_AbsensiSiswa'),
        ),
    ]
