# Generated by Django 4.0 on 2022-01-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0026_remove_pelajaran_waktu_pelajaran_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipeKelas',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='kelas',
            name='JURUSAN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kurikulum.jurusan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelas',
            name='TIPE_KELAS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tipekelas'),
            preserve_default=False,
        ),
    ]
