# Generated by Django 4.0 on 2022-01-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0027_jurusan_tipekelas_kelas_jurusan_kelas_tipe_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='TIPE_KELAS',
        ),
    ]
