# Generated by Django 4.0 on 2022-01-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0028_remove_kelas_tipe_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaOfferingKelas',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfferingKelas',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KELAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelas')),
                ('OFFERING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.namaofferingkelas')),
            ],
        ),
    ]
