# Generated by Django 4.0 on 2022-01-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0029_namaofferingkelas_offeringkelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalbelajar',
            name='KELAS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.namaofferingkelas'),
        ),
    ]
