# Generated by Django 4.0 on 2022-01-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0031_alter_jurnalbelajar_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatatertib',
            name='DAFTAR',
        ),
        migrations.AddField(
            model_name='tatatertib',
            name='DAFTAR',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.deskripsitatatertib'),
            preserve_default=False,
        ),
    ]
