# Generated by Django 4.0 on 2022-01-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0032_remove_tatatertib_daftar_tatatertib_daftar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatatertib',
            name='DAFTAR',
        ),
        migrations.AddField(
            model_name='tatatertib',
            name='KETERANGAN',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tatatertib',
            name='POIN',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeskripsiTataTertib',
        ),
    ]
