# Generated by Django 4.0 on 2022-01-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0034_alter_jadwalharian_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalharian',
            name='KELAS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.offeringkelas', unique=True),
        ),
    ]
