# Generated by Django 4.0 on 2022-01-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0036_alter_jadwalharian_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalharian',
            name='HARI',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jum`at', 'Jum`at'), ('Sabtu', 'Sabtu')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jadwalharian',
            name='KELAS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.offeringkelas'),
        ),
    ]
