# Generated by Django 4.0 on 2022-01-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0038_alter_jadwalharian_hari'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jadwalharian',
            constraint=models.UniqueConstraint(fields=('HARI', 'KELAS'), name='kurikulum_jadwalharian_unique'),
        ),
    ]
