# Generated by Django 4.0 on 2022-01-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0039_jadwalharian_kurikulum_jadwalharian_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalpelajaran',
            name='SEMESTER',
        ),
        migrations.AddField(
            model_name='jadwalpelajaran',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
    ]
