# Generated by Django 4.0 on 2022-01-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('kurikulum', '0040_remove_jadwalpelajaran_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalMengajar',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('HARI', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jum`at', 'Jum`at'), ('Sabtu', 'Sabtu')], max_length=255)),
                ('GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('KELAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.offeringkelas')),
                ('MATA_PELAJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matapelajaran')),
                ('TAHUN_AJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran')),
                ('WAKTU_PELAJARAN', models.ManyToManyField(to='kurikulum.WaktuPelajaran')),
            ],
        ),
    ]
