# Generated by Django 4.0 on 2022-01-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0041_jadwalmengajar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tahunajaran',
            constraint=models.UniqueConstraint(fields=('TAHUN_AJARAN_AWAL', 'TAHUN_AJARAN_AKHIR'), name='kurikulum_tahunajaran_unique'),
        ),
    ]
