# Generated by Django 4.0 on 2022-01-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0042_tahunajaran_kurikulum_tahunajaran_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TataTertib',
            new_name='PoinPelanggaran',
        ),
        migrations.AlterModelOptions(
            name='datasemester',
            options={'ordering': ['KE'], 'verbose_name_plural': 'Semester'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'ordering': ['TAHUN_AJARAN'], 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='ktsp',
            options={'verbose_name_plural': 'KTSP'},
        ),
        migrations.AlterModelOptions(
            name='matapelajaran',
            options={'ordering': ['NAMA'], 'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='poinpelanggaran',
            options={'ordering': ['KETERANGAN'], 'verbose_name_plural': 'Poin Pelanggaran'},
        ),
        migrations.AlterModelOptions(
            name='silabusrpb',
            options={'verbose_name_plural': 'Silabus RPB'},
        ),
        migrations.AlterModelOptions(
            name='tahunajaran',
            options={'verbose_name_plural': 'Tahun Ajaran'},
        ),
        migrations.AddConstraint(
            model_name='datasemester',
            constraint=models.UniqueConstraint(fields=('KE',), name='kurikulum_datasemester_unique'),
        ),
        migrations.AddConstraint(
            model_name='kelas',
            constraint=models.UniqueConstraint(fields=('TAHUN_AJARAN', 'TINGKATAN', 'JURUSAN'), name='kurikulum_kelas_unique'),
        ),
        migrations.AddConstraint(
            model_name='ktsp',
            constraint=models.UniqueConstraint(fields=('TAHUN_AJARAN',), name='kurikulum_ktsp_unique'),
        ),
        migrations.AddConstraint(
            model_name='matapelajaran',
            constraint=models.UniqueConstraint(fields=('KODE', 'NAMA'), name='kurikulum_matapelajaran_unique'),
        ),
        migrations.AddConstraint(
            model_name='poinpelanggaran',
            constraint=models.UniqueConstraint(fields=('KETERANGAN', 'POIN'), name='kurikulum_poinpelanggaran_unique'),
        ),
        migrations.AddConstraint(
            model_name='silabusrpb',
            constraint=models.UniqueConstraint(fields=('MATA_PELAJARAN', 'TAHUN_AJARAN', 'KELAS', 'SEMESTER'), name='kurikulum_silabusrpb_unique'),
        ),
    ]
