# Generated by Django 4.0 on 2022-01-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0043_rename_tatatertib_poinpelanggaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TataTertib',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tata Tertib',
                'ordering': ['KETERANGAN'],
            },
        ),
        migrations.AddConstraint(
            model_name='tatatertib',
            constraint=models.UniqueConstraint(fields=('KETERANGAN',), name='kurikulum_tatatertib_unique'),
        ),
    ]
