# Generated by Django 4.0 on 2022-01-09 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0044_tatatertib_tatatertib_kurikulum_tatatertib_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriTataTertib',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategori Tata Tertib',
                'ordering': ['NAMA'],
            },
        ),
        migrations.AddConstraint(
            model_name='kategoritatatertib',
            constraint=models.UniqueConstraint(fields=('NAMA',), name='kurikulum_kategoritatatertib_unique'),
        ),
        migrations.AddField(
            model_name='tatatertib',
            name='KATEGORI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kategoritatatertib'),
            preserve_default=False,
        ),
    ]
