# Generated by Django 4.0 on 2022-01-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0045_kategoritatatertib_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatatertib',
            name='KATEGORI',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kategoritatatertib'),
        ),
    ]
