# Generated by Django 4.0 on 2022-01-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0046_alter_tatatertib_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatatertib',
            name='KATEGORI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kategoritatatertib'),
        ),
    ]
