# Generated by Django 4.0 on 2022-01-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0047_alter_tatatertib_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalmengajar',
            options={'verbose_name_plural': 'Jadwal Mengajar'},
        ),
        migrations.AlterModelOptions(
            name='waktupelajaran',
            options={'ordering': ['JAM_KE']},
        ),
        migrations.AddField(
            model_name='jadwalmengajar',
            name='JUMLAH_WAKTU',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='jadwalmengajar',
            constraint=models.UniqueConstraint(fields=('KELAS', 'MATA_PELAJARAN', 'HARI'), name='kurikulum_jadwalmengajar_unique'),
        ),
    ]
