# Generated by Django 4.0 on 2022-01-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0049_alter_jadwalmengajar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalmengajar',
            options={'ordering': ['TAHUN_AJARAN', 'KELAS', 'HARI', 'JUMLAH_WAKTU'], 'verbose_name_plural': 'Jadwal Mengajar'},
        ),
        migrations.AddField(
            model_name='jadwalmengajar',
            name='TAHUN_AJARAN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.tahunajaran'),
            preserve_default=False,
        ),
    ]
