# Generated by Django 4.0 on 2022-01-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0052_remove_jurnalbelajar_kelas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalbelajar',
            name='DESKRIPSI_MATERI',
            field=models.TextField(),
        ),
    ]
