# Generated by Django 4.0 on 2022-01-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0053_alter_jurnalbelajar_deskripsi_materi'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalMingguEfektifNonEfektif',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='poinpelanggaran',
            name='KATEGORI',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kategoritatatertib'),
            preserve_default=False,
        ),
    ]
