# Generated by Django 4.0 on 2022-01-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0054_jadwalmingguefektifnonefektif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poinpelanggaran',
            name='KATEGORI',
        ),
    ]
