# Generated by Django 4.0 on 2022-01-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('kurikulum', '0056_remove_jurnalbelajar_jadwal_mengajar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarJurnalBelajar',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
                ('KELAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.offeringkelas')),
                ('MATA_PELAJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matapelajaran')),
                ('SEMESTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester')),
            ],
        ),
    ]
