# Generated by Django 4.0 on 2022-01-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0057_daftarjurnalbelajar'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarjurnalbelajar',
            name='JURNAL_BELAJAR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.jurnalbelajar'),
        ),
    ]
