# Generated by Django 4.0 on 2022-01-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0059_remove_daftarjurnalbelajar_jurnal_belajar'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalbelajar',
            name='OWNER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.daftarjurnalbelajar'),
            preserve_default=False,
        ),
    ]
