# Generated by Django 4.0 on 2022-01-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0060_jurnalbelajar_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurnalbelajar',
            old_name='OWNER',
            new_name='DAFTARKAN_KE',
        ),
    ]
