# Generated by Django 4.0 on 2022-01-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0061_rename_owner_jurnalbelajar_daftarkan_ke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurnalbelajar',
            old_name='DAFTARKAN_KE',
            new_name='DAFTAR',
        ),
    ]
