# Generated by Django 4.0 on 2022-01-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0062_rename_daftarkan_ke_jurnalbelajar_daftar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnalbelajar',
            options={'ordering': ['PERTEMUAN'], 'verbose_name_plural': 'Jurnal Belajar'},
        ),
        migrations.AddConstraint(
            model_name='jurnalbelajar',
            constraint=models.UniqueConstraint(fields=('PERTEMUAN',), name='kurikulum_jurnalbelajar_unique'),
        ),
    ]
