# Generated by Django 4.0 on 2022-01-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0064_daftarjurnalbelajar_jadwal_mengajar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftarjurnalbelajar',
            options={'ordering': ['KELAS'], 'verbose_name_plural': 'Daftar Jurnal Belajar'},
        ),
        migrations.AddConstraint(
            model_name='daftarjurnalbelajar',
            constraint=models.UniqueConstraint(fields=('JADWAL_MENGAJAR',), name='kurikulum_daftarjurnalbelajar_unique'),
        ),
    ]
