# Generated by Django 4.0 on 2022-01-13 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0065_alter_daftarjurnalbelajar_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JadwalMingguEfektifNonEfektif',
        ),
        migrations.AlterModelOptions(
            name='daftarjurnalbelajar',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='daftarjurnalbelajar',
            name='kurikulum_daftarjurnalbelajar_unique',
        ),
        migrations.RenameField(
            model_name='jadwalpekanefektifsemester',
            old_name='JUMLAH',
            new_name='JUMALAH_MINGGU_TIDAK_EFEKTIF',
        ),
        migrations.RemoveField(
            model_name='daftarjurnalbelajar',
            name='JADWAL_MENGAJAR',
        ),
        migrations.RemoveField(
            model_name='jadwalpekanaktif',
            name='PEKAN_AKTIF',
        ),
        migrations.RemoveField(
            model_name='jadwalpekanaktif',
            name='PEKAN_TIDAK_EFEKTIF',
        ),
        migrations.RemoveField(
            model_name='jadwalpekanefektifsemester',
            name='BANYAK_MINGGU',
        ),
        migrations.RemoveField(
            model_name='jadwalpekantidakefektif',
            name='KEGIATAN',
        ),
        migrations.AddField(
            model_name='jadwalpekanaktif',
            name='KELAS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpekanaktif',
            name='MATA_PELAJARAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matapelajaran'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpekanaktif',
            name='MINGGU_EFEKTIF',
            field=models.ManyToManyField(to='kurikulum.JadwalPekanEfektifSemester'),
        ),
        migrations.AddField(
            model_name='jadwalpekanaktif',
            name='MINGGU_TIDAK_EFEKTIF',
            field=models.ManyToManyField(to='kurikulum.JadwalPekanTidakEfektif'),
        ),
        migrations.AddField(
            model_name='jadwalpekanefektifsemester',
            name='JUMLAH_MINGGU',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpekanefektifsemester',
            name='JUMLAH_MINGGU_EFEKTIF',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpekanefektifsemester',
            name='KETERANGAN',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpekantidakefektif',
            name='JUMLAH_MINGGU',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpekantidakefektif',
            name='KETERANGAN',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalpekantidakefektif',
            name='URAIAN_KETERANGAN',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='KegiatanPekanTidakEfektif',
        ),
    ]
