# Generated by Django 4.0 on 2022-01-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0065_alter_daftarjurnalbelajar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftarjurnalbelajar',
            options={'verbose_name_plural': 'Daftar Jurnal Belajar'},
        ),
    ]
