# Generated by Django 4.0 on 2022-01-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0066_delete_jadwalmingguefektifnonefektif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalpekanefektifsemester',
            name='BULAN',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('Semester', 'Semester'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwalpekanaktif',
            name='KELAS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelas'),
        ),
    ]
