# Generated by Django 4.0 on 2022-01-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0068_rename_jumalah_minggu_tidak_efektif_jadwalpekanefektifsemester_jumlah_minggu_tidak_efektif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalpekantidakefektif',
            old_name='URAIAN_KETERANGAN',
            new_name='URAIAN_KEGIATAN',
        ),
    ]
