# Generated by Django 4.0 on 2022-01-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0066_alter_daftarjurnalbelajar_options'),
        ('kurikulum', '0069_rename_uraian_keterangan_jadwalpekantidakefektif_uraian_kegiatan'),
    ]

    operations = [
    ]
