# Generated by Django 4.0 on 2022-01-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0070_merge_20220113_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalMingguEfektifNonEfektif',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='daftarjurnalbelajar',
            options={'ordering': ['KELAS'], 'verbose_name_plural': 'Daftar Jurnal Belajar'},
        ),
        migrations.AddField(
            model_name='daftarjurnalbelajar',
            name='JADWAL_MENGAJAR',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.jadwalmengajar'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='daftarjurnalbelajar',
            constraint=models.UniqueConstraint(fields=('JADWAL_MENGAJAR',), name='kurikulum_daftarjurnalbelajar_unique'),
        ),
    ]
