# Generated by Django 4.0 on 2022-01-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0071_jadwalmingguefektifnonefektif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalpelajaran',
            name='JADWAL_HARIAN',
        ),
    ]
