# Generated by Django 4.0 on 2022-01-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0072_remove_jadwalpelajaran_jadwal_harian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalpelajaran',
            options={'verbose_name_plural': 'Jadwal Pelajaran'},
        ),
        migrations.AddConstraint(
            model_name='jadwalpelajaran',
            constraint=models.UniqueConstraint(fields=('TAHUN_AJARAN',), name='kurikulum_jadwalpelajaran_unique'),
        ),
    ]
