# Generated by Django 4.0 on 2022-01-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0073_alter_jadwalpelajaran_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalharian',
            name='PELAJARAN',
        ),
        migrations.RemoveField(
            model_name='mengajar',
            name='ID_GURU',
        ),
        migrations.RemoveField(
            model_name='mengajar',
            name='MATA_PELAJARAN',
        ),
        migrations.RemoveField(
            model_name='mengajar',
            name='SEMESTER',
        ),
        migrations.RemoveField(
            model_name='pelajaran',
            name='GURU',
        ),
        migrations.RemoveField(
            model_name='pelajaran',
            name='MATA_PELAJARAN',
        ),
        migrations.RemoveField(
            model_name='pelajaran',
            name='WAKTU',
        ),
        migrations.AlterModelOptions(
            name='waktupelajaran',
            options={'ordering': ['JAM_KE'], 'verbose_name_plural': 'Waktu Pelajaran'},
        ),
        migrations.DeleteModel(
            name='AbsensiSiswa',
        ),
        migrations.DeleteModel(
            name='JadwalHarian',
        ),
        migrations.DeleteModel(
            name='JadwalPelajaran',
        ),
        migrations.DeleteModel(
            name='Mengajar',
        ),
        migrations.DeleteModel(
            name='Pelajaran',
        ),
    ]
