# Generated by Django 4.0 on 2022-01-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0074_remove_jadwalharian_kelas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulanMinggu',
        ),
    ]
