# Generated by Django 4.0 on 2022-01-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0076_delete_jadwalmingguefektifnonefektif_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurusan',
            options={'verbose_name_plural': 'Jurusan'},
        ),
    ]
