# Generated by Django 4.0 on 2022-01-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
        ('kurikulum', '0077_alter_jurusan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiSiswa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KETERANGAN', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], max_length=255)),
                ('FILE_KETERANGAN', models.FileField(max_length=255, upload_to='AbsensiSiswa')),
                ('JURNAL_BELAJAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.jurnalbelajar')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
        ),
    ]
