# Generated by Django 4.0 on 2022-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0079_alter_absensisiswa_file_keterangan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jurnalbelajar',
            name='kurikulum_jurnalbelajar_unique',
        ),
        migrations.AddConstraint(
            model_name='jurnalbelajar',
            constraint=models.UniqueConstraint(fields=('PERTEMUAN', 'DAFTAR'), name='kurikulum_jurnalbelajar_unique'),
        ),
    ]
