# Generated by Django 4.0 on 2022-02-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0080_remove_jurnalbelajar_kurikulum_jurnalbelajar_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiRaport',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KELOMPOK_MATA_PELAJARAN', models.CharField(choices=[('Kelompok A (UMUM)', 'Kelompok A (UMUM)'), ('Kelompok B (UMUM)', 'Kelompok A (UMUM)'), ('Kelompok C (PEMINATAN)', 'Kelompok C (PEMINATAN)')], max_length=255)),
                ('BEBAN', models.BigIntegerField()),
                ('NILAI_PENGETAHUAN', models.BigIntegerField()),
                ('NILAI_KETERAMPILAN', models.BigIntegerField()),
                ('DESKRIPSI_PENGETAHUAN', models.CharField(max_length=255)),
                ('DESKRIPSI_KETERAMPILAN', models.CharField(max_length=255)),
                ('KELAS_SISWA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa')),
                ('MATA_PELAJARAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matapelajaran')),
                ('SEMESTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.datasemester')),
            ],
        ),
    ]
