# Generated by Django 4.0 on 2022-01-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ABSTRAK', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KatalokBuku',
            fields=[
                ('REGISTER', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=255)),
                ('JUDUL', models.CharField(max_length=255)),
                ('VOLUME', models.BigIntegerField()),
                ('EDISI', models.BigIntegerField()),
                ('DUPLIKAT', models.BigIntegerField()),
                ('NOMER_DEWEY', models.CharField(max_length=255)),
                ('KODE_AUTHOR', models.CharField(max_length=255)),
                ('KODE_JUDUL', models.CharField(max_length=255)),
                ('TAHUN_TERBIT', models.CharField(max_length=255)),
                ('KOTA_PENERBIT', models.CharField(max_length=255)),
                ('PENERBIT', models.CharField(max_length=255)),
                ('DESKRIPSI_FISIK', models.CharField(max_length=255)),
                ('INDEX', models.CharField(max_length=255)),
                ('BIBLIOGRAPHY', models.CharField(max_length=255)),
                ('HARGA', models.CharField(max_length=255)),
                ('CATATAN_DONASI', models.CharField(max_length=255)),
                ('TANGGAL_PENERIMAAN', models.DateField(max_length=255)),
                ('DATA_ENTRY', models.DateField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Data Book Main',
            },
        ),
        migrations.CreateModel(
            name='KunjunganGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TANGGAL_KUNJUNGAN', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KunjunganSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TANGGAL_KUNJUNGAN', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanGuruPanjang',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KELAS', models.CharField(default='', max_length=255)),
                ('ALAMAT', models.CharField(default='', max_length=255)),
                ('TANGGAL_PINJAM', models.CharField(default='', max_length=255)),
                ('NO_BARCODE', models.CharField(default='', max_length=255)),
                ('JUMLAH', models.CharField(default='', max_length=255)),
                ('TANDA_TANGAN', models.CharField(default='', max_length=255)),
                ('KETERANGAN', models.CharField(default='', max_length=255)),
                ('LOAN_STATUS', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=255)),
                ('IS_PRINTED', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoanGuruPendek',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('OUT_DATE', models.DateField()),
                ('DUE_DATE', models.DateField()),
                ('LOAN_STATUS', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=255)),
                ('IS_PRINTED', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoanSiswaPanjang',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KELAS', models.CharField(default='', max_length=255)),
                ('ALAMAT', models.CharField(default='', max_length=255)),
                ('TANGGAL_PINJAM', models.CharField(default='', max_length=255)),
                ('NO_BARCODE', models.CharField(default='', max_length=255)),
                ('JUMLAH', models.CharField(default='', max_length=255)),
                ('TANDA_TANGAN', models.CharField(default='', max_length=255)),
                ('KETERANGAN', models.CharField(default='', max_length=255)),
                ('LOAN_STATUS', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=255)),
                ('IS_PRINTED', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoanSiswaPendek',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('OUT_DATE', models.DateField()),
                ('DUE_DATE', models.DateField()),
                ('LOAN_STATUS', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=255)),
                ('IS_PRINTED', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KODE_LOKASI', models.CharField(max_length=255)),
                ('NAMA_LOKASI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LokasiSpesifik',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('LOKASI_SPESIFIK', models.CharField(max_length=255)),
                ('NAMA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KODE_OPERATOR', models.CharField(max_length=255)),
                ('NAMA_OPERATOR', models.CharField(max_length=255)),
                ('NAMA_LENGKAP', models.CharField(max_length=255)),
                ('UNIT', models.CharField(max_length=255)),
                ('PATRON_ACC', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('BOOK_ACC', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('SCIENCE_ACC', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('SERIAL_ACC', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('CIRCULATION_ACC', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('HAK_NEGO_DENDA', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('HAK_KATALOG', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('HAK_ABSENSI', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pendanaan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KODE_PENDANAAN', models.CharField(max_length=255)),
                ('NAMA_PENDANAAN', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipeBahasa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KODE_BAHASA', models.CharField(max_length=255)),
                ('BAHASA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipeBuku',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KODE_TIPE', models.CharField(max_length=255)),
                ('NAMA_TIPE', models.CharField(max_length=255)),
                ('LAMA_PINJAM', models.BigIntegerField()),
                ('DENDA', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipeMedia',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KODE_MEDIA', models.CharField(max_length=255)),
                ('NAMA_MEDIA', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TIPE MEDIA',
            },
        ),
        migrations.AddConstraint(
            model_name='tipemedia',
            constraint=models.UniqueConstraint(fields=('KODE_MEDIA', 'NAMA_MEDIA'), name='perpustakaan_tipemedia_unique'),
        ),
        migrations.AddField(
            model_name='loansiswapendek',
            name='NIS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='loansiswapendek',
            name='OPERATOR_CODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.operator'),
        ),
        migrations.AddField(
            model_name='loansiswapendek',
            name='REGISTER',
            field=models.ManyToManyField(to='perpustakaan.KatalokBuku'),
        ),
        migrations.AddField(
            model_name='loansiswapanjang',
            name='NIS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='loansiswapanjang',
            name='OPERATOR_CODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.operator'),
        ),
        migrations.AddField(
            model_name='loansiswapanjang',
            name='REGISTER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.katalokbuku'),
        ),
        migrations.AddField(
            model_name='loangurupendek',
            name='NIP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='loangurupendek',
            name='OPERATOR_CODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.operator'),
        ),
        migrations.AddField(
            model_name='loangurupendek',
            name='REGISTER',
            field=models.ManyToManyField(to='perpustakaan.KatalokBuku'),
        ),
        migrations.AddField(
            model_name='loangurupanjang',
            name='NIP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='loangurupanjang',
            name='OPERATOR_CODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.operator'),
        ),
        migrations.AddField(
            model_name='loangurupanjang',
            name='REGISTER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.katalokbuku'),
        ),
        migrations.AddField(
            model_name='kunjungansiswa',
            name='NIS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
        ),
        migrations.AddField(
            model_name='kunjunganguru',
            name='NIP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='katalokbuku',
            name='BAHASA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tipebahasa'),
        ),
        migrations.AddField(
            model_name='katalokbuku',
            name='KODE_DONASI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pendanaan'),
        ),
        migrations.AddField(
            model_name='katalokbuku',
            name='KODE_LOKASI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.lokasi'),
        ),
        migrations.AddField(
            model_name='katalokbuku',
            name='KODE_MEDIA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tipemedia'),
        ),
        migrations.AddField(
            model_name='katalokbuku',
            name='LOKASI_SPESIFIK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.lokasispesifik'),
        ),
        migrations.AddField(
            model_name='katalokbuku',
            name='OPERATOR_CODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.operator'),
        ),
        migrations.AddField(
            model_name='katalokbuku',
            name='TIPE_KODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tipebuku'),
        ),
        migrations.AddField(
            model_name='abstrak',
            name='REGISTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.katalokbuku'),
        ),
        migrations.AddConstraint(
            model_name='katalokbuku',
            constraint=models.UniqueConstraint(fields=('REGISTER',), name='perpustakaan_katalokbuku_unique'),
        ),
    ]
