# Generated by Django 4.0 on 2022-01-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KODE_AUTHOR', models.CharField(max_length=255)),
                ('NAMA_AUTHOR', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='DUPLIKAT',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='EDISI',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='ISBN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='VOLUME',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='KODE_AUTHOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.author'),
        ),
    ]
