# Generated by Django 4.0 on 2022-03-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasibuku',
            name='DUPLIKAT',
            field=models.PositiveBigIntegerField(),
        ),
    ]
