# Generated by Django 4.0 on 2022-03-07 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_alter_donasibuku_duplikat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasibuku',
            name='TANGGAL_PENERIMAAN',
            field=models.DateTimeField(default=datetime.date.today, max_length=255),
        ),
    ]
