# Generated by Django 4.0 on 2022-03-03 07:51

import adistetsa.custom_function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_remove_tipebuku_denda_remove_tipebuku_lama_pinjam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='NAMA_AUTHOR',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.paksa_huruf_besar]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='EDISI',
            field=models.CharField(blank=True, max_length=255, validators=[adistetsa.custom_function.validasi_integer]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='HARGA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.validasi_integer]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='INDEX',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='ISBN',
            field=models.CharField(blank=True, max_length=255, validators=[adistetsa.custom_function.validasi_integer]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='JUDUL',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='KOTA_PENERBIT',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='NOMER_DEWEY',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.validasi_integer]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='PENERBIT',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='REGISTER',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[adistetsa.custom_function.validasi_integer]),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='VOLUME',
            field=models.CharField(blank=True, max_length=255, validators=[adistetsa.custom_function.validasi_integer]),
        ),
        migrations.AlterField(
            model_name='lokasi',
            name='NAMA_LOKASI',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='lokasispesifik',
            name='NAMA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='pendanaan',
            name='NAMA_PENDANAAN',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='tipemedia',
            name='NAMA_MEDIA',
            field=models.CharField(max_length=255, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
    ]
