# Generated by Django 4.0 on 2022-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_author_alter_katalokbuku_duplikat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalokbuku',
            name='BIBLIOGRAPHY',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='EDISI',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='VOLUME',
            field=models.CharField(max_length=255),
        ),
    ]
