# Generated by Django 4.0 on 2022-03-04 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_alter_donasibuku_duplikat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasibuku',
            name='TANGGAL_PENERIMAAN',
            field=models.DateField(default=datetime.date.today, max_length=255),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='DATA_ENTRY',
            field=models.DateField(default=datetime.date.today, max_length=255),
        ),
        migrations.AlterField(
            model_name='kunjunganguru',
            name='TANGGAL_KUNJUNGAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='kunjungansiswa',
            name='TANGGAL_KUNJUNGAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamanguru',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamansiswa',
            name='TANGGAL_PENGAJUAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanguru',
            name='TANGGAL_PEMINJAMAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanguru',
            name='TANGGAL_PENGEMBALIAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamansiswa',
            name='TANGGAL_PEMINJAMAN',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamansiswa',
            name='TANGGAL_PENGEMBALIAN',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
