# Generated by Django 4.0 on 2022-01-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_alter_katalokbuku_bibliography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalokbuku',
            name='EDISI',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='katalokbuku',
            name='VOLUME',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
