# Generated by Django 4.0 on 2022-03-07 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_alter_donasibuku_tanggal_penerimaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasibuku',
            name='TANGGAL_PENERIMAAN',
            field=models.DateField(default=datetime.date.today, max_length=255),
        ),
    ]
