# Generated by Django 4.0 on 2022-01-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_alter_katalokbuku_edisi_alter_katalokbuku_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatalogBuku',
            fields=[
                ('REGISTER', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ISBN', models.CharField(blank=True, max_length=255)),
                ('JUDUL', models.CharField(max_length=255)),
                ('VOLUME', models.CharField(blank=True, max_length=255)),
                ('EDISI', models.CharField(blank=True, max_length=255)),
                ('DUPLIKAT', models.BigIntegerField()),
                ('NOMER_DEWEY', models.CharField(max_length=255)),
                ('KODE_JUDUL', models.CharField(max_length=255)),
                ('TAHUN_TERBIT', models.CharField(max_length=255)),
                ('KOTA_PENERBIT', models.CharField(max_length=255)),
                ('PENERBIT', models.CharField(max_length=255)),
                ('DESKRIPSI_FISIK', models.CharField(max_length=255)),
                ('INDEX', models.CharField(max_length=255)),
                ('BIBLIOGRAPHY', models.CharField(blank=True, max_length=255)),
                ('HARGA', models.CharField(max_length=255)),
                ('CATATAN_DONASI', models.CharField(max_length=255)),
                ('TANGGAL_PENERIMAAN', models.DateField(max_length=255)),
                ('DATA_ENTRY', models.DateField(max_length=255)),
                ('BAHASA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tipebahasa')),
                ('KODE_AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.author')),
                ('KODE_DONASI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pendanaan')),
                ('KODE_LOKASI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.lokasi')),
                ('KODE_MEDIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tipemedia')),
                ('LOKASI_SPESIFIK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.lokasispesifik')),
                ('OPERATOR_CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.operator')),
                ('TIPE_KODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tipebuku')),
            ],
            options={
                'verbose_name_plural': 'Data Book Main',
            },
        ),
        migrations.AlterField(
            model_name='abstrak',
            name='REGISTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.katalogbuku'),
        ),
        migrations.AlterField(
            model_name='loangurupanjang',
            name='REGISTER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.katalogbuku'),
        ),
        migrations.AlterField(
            model_name='loangurupendek',
            name='REGISTER',
            field=models.ManyToManyField(to='perpustakaan.KatalogBuku'),
        ),
        migrations.AlterField(
            model_name='loansiswapanjang',
            name='REGISTER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.katalogbuku'),
        ),
        migrations.AlterField(
            model_name='loansiswapendek',
            name='REGISTER',
            field=models.ManyToManyField(to='perpustakaan.KatalogBuku'),
        ),
        migrations.DeleteModel(
            name='KatalokBuku',
        ),
        migrations.AddConstraint(
            model_name='katalogbuku',
            constraint=models.UniqueConstraint(fields=('REGISTER',), name='perpustakaan_katalogbuku_unique'),
        ),
    ]
