# Generated by Django 4.0 on 2022-01-17 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('perpustakaan', '0005_katalogbuku_alter_abstrak_register_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='NAMA_LENGKAP',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='NAMA_OPERATOR',
        ),
        migrations.AlterField(
            model_name='operator',
            name='KODE_OPERATOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
