# Generated by Django 4.0 on 2022-01-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('perpustakaan', '0006_remove_operator_nama_lengkap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='BOOK_ACC',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='CIRCULATION_ACC',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='HAK_ABSENSI',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='HAK_KATALOG',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='HAK_NEGO_DENDA',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='PATRON_ACC',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='SCIENCE_ACC',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='SERIAL_ACC',
        ),
        migrations.AddField(
            model_name='operator',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operator',
            name='KODE_OPERATOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
