# Generated by Django 4.0 on 2022-02-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0007_remove_abstrak_abstrak_alter_katalogbukucopy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstrak',
            name='ABSTRAK',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='katalogbukucopy',
            name='STATUS',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanguru',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamansiswa',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255),
        ),
    ]
