# Generated by Django 4.0 on 2022-01-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('perpustakaan', '0009_operator_object_id_alter_operator_kode_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='operator',
            name='KODE_OPERATOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
