# Generated by Django 4.0 on 2022-01-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0010_remove_operator_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskripsiFisik',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JUMLAH_HALAMAN', models.PositiveBigIntegerField(blank=True)),
                ('TEBAL_BUKU', models.PositiveBigIntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='DESKRIPSI_FISIK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.deskripsifisik'),
        ),
    ]
