# Generated by Django 4.0 on 2022-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0011_deskripsifisik_alter_katalogbuku_deskripsi_fisik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalogbuku',
            name='DESKRIPSI_FISIK',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='DeskripsiFisik',
        ),
    ]
