# Generated by Django 4.0 on 2022-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0012_alter_katalogbuku_deskripsi_fisik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunTerbit',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAHUN_TERBIT', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='KODE_JUDUL',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='katalogbuku',
            name='TAHUN_TERBIT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.tahunterbit'),
        ),
    ]
