# Generated by Django 4.0 on 2022-01-19 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
        ('perpustakaan', '0013_tahunterbit_alter_katalogbuku_kode_judul_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeminjamanSiswaPendek',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_PEMINJAMAN', models.DateField()),
                ('TANGGAL_KEMBALI', models.DateField()),
                ('STATUS_PEMINJAMAN', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=255)),
                ('STATUS_CETAKAN', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=255)),
                ('BUKU', models.ManyToManyField(to='perpustakaan.KatalogBuku')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
                ('OPERATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.operator')),
            ],
        ),
        migrations.DeleteModel(
            name='LoanSiswaPendek',
        ),
    ]
