# Generated by Django 4.0 on 2022-01-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0014_peminjamansiswapendek_delete_loansiswapendek'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='katalogbuku',
            name='perpustakaan_katalogbuku_unique',
        ),
        migrations.AddField(
            model_name='peminjamansiswapendek',
            name='STATUS_PENGAJUAN',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peminjamansiswapendek',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Tenggat', 'Tenggat')], max_length=255),
        ),
    ]
