# Generated by Django 4.0 on 2022-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0015_alter_katalogbukucopy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalogbukucopy',
            name='STATUS',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanguru',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamansiswa',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Pengajuan', 'Pengajuan'), ('Tenggat', 'Tenggat'), ('Hilang', 'Hilang'), ('Ditolak', 'Ditolak'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Sedang Dipinjam', max_length=255),
        ),
    ]
