# Generated by Django 4.0 on 2022-01-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0015_remove_katalogbuku_perpustakaan_katalogbuku_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamansiswapendek',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], max_length=255),
        ),
        migrations.AlterField(
            model_name='peminjamansiswapendek',
            name='STATUS_PENGAJUAN',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui')], max_length=255),
        ),
        migrations.CreateModel(
            name='KatalokBukuCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGISTER_COPY', models.CharField(max_length=255)),
                ('DATA_BUKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.katalogbuku')),
            ],
        ),
    ]
