# Generated by Django 4.0 on 2022-01-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0018_alter_peminjamansiswapendek_buku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalogbukucopy',
            name='STATUS',
            field=models.CharField(choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='peminjamansiswapendek',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(blank=True, choices=[('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], max_length=255),
        ),
    ]
