# Generated by Django 4.0 on 2022-01-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
        ('perpustakaan', '0019_katalogbukucopy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamansiswapendek',
            name='STATUS_PENGAJUAN',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], max_length=255),
        ),
        migrations.CreateModel(
            name='RiwayatPeminjamanSiswa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_PEMINJAMAN', models.DateField()),
                ('TANGGAL_PENGEMBALIAN', models.DateField()),
                ('JANGKA_PEMINJAMAN', models.CharField(blank=True, choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('BUKU', models.ManyToManyField(to='perpustakaan.KatalogBukuCopy')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanPeminjamanSiswa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('STATUS_PENGAJUAN', models.CharField(blank=True, choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], max_length=255)),
                ('JANGKA_PEMINJAMAN', models.CharField(blank=True, choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('BUKU', models.ManyToManyField(to='perpustakaan.KatalogBukuCopy')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
        ),
    ]
