# Generated by Django 4.0 on 2022-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0020_alter_peminjamansiswapendek_status_pengajuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanpeminjamansiswa',
            name='FILE_TTD_PENGAJUAN',
            field=models.FileField(blank=True, max_length=255, upload_to='Dokumen_KTSP'),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamansiswa',
            name='FILE_TTD_PENGAJUAN',
            field=models.FileField(blank=True, max_length=255, upload_to='Dokumen_KTSP'),
        ),
        migrations.AddField(
            model_name='riwayatpeminjamansiswa',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='katalogbukucopy',
            name='STATUS',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='peminjamansiswapendek',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(blank=True, choices=[('Tenggat', 'Tenggat'), ('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamansiswa',
            name='STATUS_PENGAJUAN',
            field=models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255),
        ),
    ]
