# Generated by Django 4.0 on 2022-01-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0002_rename_no_telp_dataguru_hp_and_more'),
        ('perpustakaan', '0021_pengajuanpeminjamansiswa_file_ttd_pengajuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalogbukucopy',
            name='STATUS',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='peminjamansiswapendek',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(blank=True, choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pengajuanpeminjamansiswa',
            name='FILE_TTD_PENGAJUAN',
            field=models.FileField(blank=True, max_length=255, upload_to='Dokumen_Peminjaman_Jangka_Panjang_Siswa'),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamansiswa',
            name='FILE_TTD_PENGAJUAN',
            field=models.FileField(blank=True, max_length=255, upload_to='Dokumen_Peminjaman_Jangka_Panjang_Siswa'),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamansiswa',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.CreateModel(
            name='RiwayatPeminjamanGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_PEMINJAMAN', models.DateField()),
                ('TANGGAL_PENGEMBALIAN', models.DateField()),
                ('JANGKA_PEMINJAMAN', models.CharField(blank=True, choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('FILE_TTD_PENGAJUAN', models.FileField(blank=True, max_length=255, upload_to='Dokumen_Peminjaman_Jangka_Panjang_Guru')),
                ('STATUS_PEMINJAMAN', models.CharField(choices=[('Sudah Dikembalikan', 'Sudah Dikembalikan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Tenggat', 'Tenggat')], default='Sedang Dipinjam', max_length=255)),
                ('BUKU', models.ManyToManyField(to='perpustakaan.KatalogBukuCopy')),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanPeminjamanGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL_PENGAJUAN', models.DateField()),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Pengajuan', 'Pengajuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=255)),
                ('JANGKA_PEMINJAMAN', models.CharField(blank=True, choices=[('Jangka Pendek', 'Jangka Pendek'), ('Jangka Panjang', 'Jangka Panjang')], max_length=255)),
                ('FILE_TTD_PENGAJUAN', models.FileField(blank=True, max_length=255, upload_to='Dokumen_Peminjaman_Jangka_Panjang_Guru')),
                ('BUKU', models.ManyToManyField(to='perpustakaan.KatalogBukuCopy')),
                ('DATA_GURU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru')),
            ],
        ),
    ]
