# Generated by Django 4.0 on 2022-01-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0024_alter_katalogbukucopy_status_and_more'),
        ('perpustakaan', '0024_remove_katalogbukucopy_status_peminjaman_and_more'),
    ]

    operations = [
    ]
