# Generated by Django 4.0 on 2022-01-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0025_merge_20220127_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loangurupendek',
            name='NIP',
        ),
        migrations.RemoveField(
            model_name='loangurupendek',
            name='OPERATOR_CODE',
        ),
        migrations.RemoveField(
            model_name='loangurupendek',
            name='REGISTER',
        ),
        migrations.RemoveField(
            model_name='loansiswapanjang',
            name='NIS',
        ),
        migrations.RemoveField(
            model_name='loansiswapanjang',
            name='OPERATOR_CODE',
        ),
        migrations.RemoveField(
            model_name='loansiswapanjang',
            name='REGISTER',
        ),
        migrations.RemoveField(
            model_name='peminjamansiswapendek',
            name='BUKU',
        ),
        migrations.RemoveField(
            model_name='peminjamansiswapendek',
            name='NIS',
        ),
        migrations.RemoveField(
            model_name='peminjamansiswapendek',
            name='OPERATOR',
        ),
        migrations.AlterField(
            model_name='katalogbukucopy',
            name='STATUS',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Sudah Dikembalikan', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamanguru',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.AlterField(
            model_name='riwayatpeminjamansiswa',
            name='STATUS_PEMINJAMAN',
            field=models.CharField(choices=[('Tenggat', 'Tenggat'), ('Pengajuan', 'Pengajuan'), ('Sedang Dipinjam', 'Sedang Dipinjam'), ('Sudah Dikembalikan', 'Sudah Dikembalikan')], default='Sedang Dipinjam', max_length=255),
        ),
        migrations.DeleteModel(
            name='LoanGuruPanjang',
        ),
        migrations.DeleteModel(
            name='LoanGuruPendek',
        ),
        migrations.DeleteModel(
            name='LoanSiswaPanjang',
        ),
        migrations.DeleteModel(
            name='PeminjamanSiswaPendek',
        ),
    ]
