from django.urls.conf import path

from .views import *

urlpatterns = [
    path('data_siswa', DataSiswaListView.as_view(), name='data_siswa'),
    path('data_siswa/<int:siswa_id>', DataSiswaDetailView.as_view()),
    path('data_orang_tua', DataOrangTuaListView.as_view(), name='data_orang_tua'),
    path('data_orang_tua/<int:orangtua_id>', DataOrangTuaDetailView.as_view()),
    path('data_guru', DataGuruListView.as_view(), name='data_guru'),
    path('data_guru/<int:guru_id>', DataGuruDetailView.as_view()),
    path('data_karyawan', DataKaryawanListView.as_view(), name='data_karyawan'),
    path('data_karyawan/<int:karyawan_id>', DataKaryawanDetailView.as_view()),
    path('data_guru_kompetensi', DataKompetensiGuruListView.as_view(), name='data_kompetensi_guru'),
    path('data_guru_kompetensi/<int:pk>', DataKompetensiGuruDetailView.as_view(), name='data_kompetensi_guru'),
    path('data_karyawan_kompetensi', DataKompetensiKaryawanListView.as_view(), name='data_kompetensi_karyawan'),
    path('data_karyawan_kompetensi/<int:pk>', DataKompetensiKaryawanDetailView.as_view(), name='data_kompetensi_karyawan'),
    path('data_guru_anak', DataAnakGuruListView.as_view()),
    path('data_guru_anak/<int:pk>', DataAnakGuruDetailView.as_view()),
    path('data_guru_beasiswa', DataBeasiswaGuruListView.as_view()),
    path('data_guru_beasiswa/<int:pk>', DataBeasiswaGuruDetailView.as_view()),
    path('data_guru_buku', DataBukuGuruListView.as_view()),
    path('data_guru_buku/<int:pk>', DataBukuGuruDetailView.as_view()),
    path('data_guru_diklat', DataDiklatGuruListView.as_view()),
    path('data_guru_diklat/<int:pk>', DataDiklatGuruDetailView.as_view()),
    path('data_guru_karya_tulis', DataKaryaTulisGuruListView.as_view()),
    path('data_guru_karya_tulis/<int:pk>', DataKaryaTulisGuruDetailView.as_view()),
    path('data_guru_kesejahteraan', DataKesejahteraanGuruListView.as_view()),
    path('data_guru_kesejahteraan/<int:pk>', DataKesejahteraanGuruDetailView.as_view()),
    path('data_guru_tunjangan', DataTunjanganGuruListView.as_view()),
    path('data_guru_tunjangan/<int:pk>', DataTunjanganGuruDetailView.as_view()),
    path('data_guru_tugas_tambahan', DataTugasTambahanGuruListView.as_view()),
    path('data_guru_tugas_tambahan/<int:pk>', DataTugasTambahanGuruDetailView.as_view()),
    path('data_guru_penghargaan', DataPenghargaanGuruListView.as_view()),
    path('data_guru_penghargaan/<int:pk>', DataPenghargaanGuruDetailView.as_view()),
    path('data_guru_nilai_tes', DataNilaiTesGuruListView.as_view()),
    path('data_guru_nilai_tes/<int:pk>', DataNilaiTesGuruDetailView.as_view()),
    path('data_guru_riwayat_gaji_berkala', DataRiwayatGajiBerkalaGuruListView.as_view()),
    path('data_guru_riwayat_gaji_berkala/<int:pk>', DataRiwayatGajiBerkalaGuruDetailView.as_view()),
    path('data_guru_riwayat_jabatan_struktural', DataRiwayatJabatanStrukturalGuruListView.as_view()),
    path('data_guru_riwayat_jabatan_struktural/<int:pk>', DataRiwayatJabatanStrukturalGuruDetailView.as_view()),
    path('data_guru_riwayat_kepangkatan', DataRiwayatKepangkatanGuruListView.as_view()),
    path('data_guru_riwayat_kepangkatan/<int:pk>', DataRiwayatKepangkatanGuruDetailView.as_view()),
    path('data_guru_riwayat_pendidikan_formal', DataRiwayatPendidikanFormalGuruListView.as_view()),
    path('data_guru_riwayat_pendidikan_formal/<int:pk>', DataRiwayatPendidikanFormalGuruDetailView.as_view()),
    path('data_guru_riwayat_sertifikasi', DataRiwayatSertifikasiGuruListView.as_view()),
    path('data_guru_riwayat_sertifikasi/<int:pk>', DataRiwayatSertifikasiGuruDetailView.as_view()),
    path('data_guru_riwayat_jabatan_fungsional', DataRiwayatJabatanFungsionalGuruListView.as_view()),
    path('data_guru_riwayat_jabatan_fungsional/<int:pk>', DataRiwayatJabatanFungsionalGuruDetailView.as_view()),
    path('data_guru_riwayat_karir', DataRiwayatKarirGuruListView.as_view()),
    path('data_guru_riwayat_karir/<int:pk>', DataRiwayatKarirGuruDetailView.as_view()),
    path('data_anak_karyawan', DataAnakKaryawanListView.as_view()),
    path('data_anak_karyawan/<int:pk>', DataAnakKaryawanDetailView.as_view()),
    path('data_beasiswa_karyawan', DataBeasiswaKaryawanListView.as_view()),
    path('data_beasiswa_karyawan/<int:pk>', DataBeasiswaKaryawanDetailView.as_view()),
    path('data_buku_karyawan', DataBukuKaryawanListView.as_view()),
    path('data_buku_karyawan/<int:pk>', DataBukuKaryawanDetailView.as_view()),
    path('data_diklat_karyawan', DataDiklatKaryawanListView.as_view()),
    path('data_diklat_karyawan/<int:pk>', DataDiklatKaryawanDetailView.as_view()),
    path('data_karya_tulis_karyawan', DataKaryaTulisKaryawanListView.as_view()),
    path('data_karya_tulis_karyawan/<int:pk>', DataKaryaTulisKaryawanDetailView.as_view()),
    path('data_kesejahteraan_karyawan', DataKesejahteraanKaryawanListView.as_view()),
    path('data_kesejahteraan_karyawan/<int:pk>', DataKesejahteraanKaryawanDetailView.as_view()),
    path('data_tunjangan_karyawan', DataTunjanganKaryawanListView.as_view()),
    path('data_tunjangan_karyawan/<int:pk>', DataTunjanganKaryawanDetailView.as_view()),
    path('data_tugas_tambahan_karyawan', DataTugasTambahanKaryawanListView.as_view()),
    path('data_tugas_tambahan_karyawan/<int:pk>', DataTugasTambahanKaryawanDetailView.as_view()),
    path('data_penghargaan_karyawan', DataPenghargaanKaryawanListView.as_view()),
    path('data_penghargaann_karyawan/<int:pk>', DataPenghargaanKaryawanDetailView.as_view()),
    path('data_nilai_tes_karyawan', DataNilaiTesKaryawanListView.as_view()),
    path('data_nilai_tes_karyawan/<int:pk>', DataNilaiTesKaryawanDetailView.as_view()),
    path('data_riwayat_gaji_berkala_karyawan', DataRiwayatGajiBerkalaKaryawanListView.as_view()),
    path('data_riwayat_gaji_berkala_karyawan/<int:pk>', DataRiwayatGajiBerkalaKaryawanDetailView.as_view()),
    path('data_riwayat_jabatan_struktural_karyawan', DataRiwayatJabatanStrukturalKaryawanListView.as_view()),
    path('data_riwayat_jabatan_struktural_karyawan/<int:pk>', DataRiwayatJabatanStrukturalKaryawanDetailView.as_view()),
    path('data_riwayat_kepangkatan_karyawan', DataRiwayatKepangkatanKaryawanListView.as_view()),
    path('data_riwayat_kepangkatan_karyawan/<int:pk>', DataRiwayatKepangkatanKaryawanDetailView.as_view()),
    path('data_riwayat_pendidikan_formal_karyawan', DataRiwayatPendidikanFormalKaryawanListView.as_view()),
    path('data_riwayat_pendidikan_formal_karyawan/<int:pk>', DataRiwayatPendidikanFormalKaryawanDetailView.as_view()),
    path('data_riwayat_sertifikasi_karyawan', DataRiwayatSertifikasiKaryawanListView.as_view()),
    path('data_riwayat_sertifikasi_karyawan/<int:pk>', DataRiwayatSertifikasiKaryawanDetailView.as_view()),
    path('data_riwayat_jabatan_fungsional_karyawan', DataRiwayatJabatanFungsionalKaryawanListView.as_view()),
    path('data_riwayat_jabatan_fungsional_karyawan/<int:pk>', DataRiwayatJabatanFungsionalKaryawanDetailView.as_view()),
    path('data_riwayat_karir_karyawan', DataRiwayatKarirKaryawanListView.as_view()),
    path('data_riwayat_karir_karyawan/<int:pk>', DataRiwayatKarirKaryawanDetailView.as_view()),
]