from django.urls.conf import path

from .views import *

urlpatterns = [
    path('data_siswa', DataSiswaListView.as_view()),
    path('data_siswa/<int:siswa_id>', DataSiswaDetailView.as_view()),
    path('data_orang_tua', DataOrangTuaListView.as_view()),
    path('data_orang_tua/<int:orangtua_id>', DataOrangTuaDetailView.as_view()),
    path('data_guru', DataGuruListView.as_view()),
    path('data_guru/<int:guru_id>', DataGuruDetailView.as_view()),
    path('data_karyawan', DataKaryawanListView.as_view()),
    path('data_karyawan/<int:karyawan_id>', DataKaryawanDetailView.as_view()),
    path('data_guru_kompetensi', DataKompetensiGuruListView.as_view()),
    path('data_guru_kompetensi/<int:pk>', DataKompetensiGuruDetailView.as_view()),
    path('data_anak_karyawan', DataAnakKaryawanListView.as_view()),
    path('data_anak_karyawan/<int:pk>', DataAnakKaryawanDetailView.as_view()),
    path('data_beasiswa_karyawan', DataBeasiswaKaryawanListView.as_view()),
    path('data_beasiswa_karyawan/<int:pk>', DataBeasiswaKaryawanDetailView.as_view()),
    path('data_buku_karyawan', DataBukuKaryawanListView.as_view()),
    path('data_buku_karyawan/<int:pk>', DataBukuKaryawanDetailView.as_view()),
    path('data_diklat_karyawan', DataDiklatKaryawanListView.as_view()),
    path('data_diklat_karyawan/<int:pk>', DataDiklatKaryawanDetailView.as_view()),
    path('data_karya_tulis_karyawan', DataKaryaTulisKaryawanListView.as_view()),
    path('data_karya_tulis_karyawan/<int:pk>', DataKaryaTulisKaryawanDetailView.as_view()),
    path('data_kesejahteraan_karyawan', DataKesejahteraanKaryawanListView.as_view()),
    path('data_kesejahteraan_karyawan/<int:pk>', DataKesejahteraanKaryawanDetailView.as_view()),
    path('data_tunjangan_karyawan', DataTunjanganKaryawanListView.as_view()),
    path('data_tunjangan_karyawan/<int:pk>', DataTunjanganKaryawanDetailView.as_view()),
    path('data_tugas_tambahan_karyawan', DataTugasTambahanKaryawanListView.as_view()),
    path('data_tugas_tambahan_karyawan/<int:pk>', DataTugasTambahanKaryawanDetailView.as_view()),
    path('data_penghargaan_karyawan', DataPenghargaanKaryawanListView.as_view()),
    path('data_penghargaann_karyawan/<int:pk>', DataPenghargaanKaryawanDetailView.as_view()),
    path('data_nilai_tes_karyawan', DataNilaiTesKaryawanListView.as_view()),
    path('data_nilai_tes_karyawan/<int:pk>', DataNilaiTesKaryawanDetailView.as_view()),
    path('data_riwayat_gaji_berkala_karyawan', DataRiwayatGajiBerkalaKaryawanListView.as_view()),
    path('data_riwayat_gaji_berkala_karyawan/<int:pk>', DataRiwayatGajiBerkalaKaryawanDetailView.as_view()),
    path('data_riwayat_jabatan_struktural_karyawan', DataRiwayatJabatanStrukturalKaryawanListView.as_view()),
    path('data_riwayat_jabatan_struktural_karyawan/<int:pk>', DataRiwayatJabatanStrukturalKaryawanDetailView.as_view()),
    path('data_riwayat_kepangkatan_karyawan', DataRiwayatKepangkatanKaryawanListView.as_view()),
    path('data_riwayat_kepangkatan_karyawan/<int:pk>', DataRiwayatKepangkatanKaryawanDetailView.as_view()),
    path('data_riwayat_pendidikan_formal_karyawan', DataRiwayatPendidikanFormalKaryawanListView.as_view()),
    path('data_riwayat_pendidikan_formal_karyawan/<int:pk>', DataRiwayatPendidikanFormalKaryawanDetailView.as_view()),
    path('data_riwayat_sertifikasi_karyawan', DataRiwayatSertifikasiKaryawanListView.as_view()),
    path('data_riwayat_sertifikasi_karyawan/<int:pk>', DataRiwayatSertifikasiKaryawanDetailView.as_view()),
    path('data_riwayat_jabatan_fungsional_karyawan', DataRiwayatJabatanFungsionalKaryawanListView.as_view()),
    path('data_riwayat_jabatan_fungsional_karyawan/<int:pk>', DataRiwayatJabatanFungsionalKaryawanDetailView.as_view()),
    path('data_riwayat_karir_karyawan', DataRiwayatKarirKaryawanListView.as_view()),
    path('data_riwayat_karir_karyawan/<int:pk>', DataRiwayatKarirKaryawanDetailView.as_view()),

]