from django.urls.conf import path

from .views import *

urlpatterns = [
    path('data_siswa', DataSiswaListView.as_view()),
    path('data_siswa/<int:siswa_id>', DataSiswaDetailView.as_view()),
    path('data_orang_tua', DataOrangTuaListView.as_view()),
    path('data_orang_tua/<int:orangtua_id>', DataOrangTuaDetailView.as_view()),
    path('data_guru', DataGuruListView.as_view()),
    path('data_guru/<int:guru_id>', DataGuruDetailView.as_view()),
    path('data_karyawan', DataKaryawanListView.as_view()),
    path('data_karyawan/<int:karyawan_id>', DataKaryawanDetailView.as_view()),
    path('data_guru_kompetensi', DataKompetensiGuruListView.as_view()),
    path('data_guru_kompetensi/<int:pk>', DataKompetensiGuruDetailView.as_view()),
    path('data_karyawan_kompetensi', DataKompetensiKaryawanListView.as_view()),
    path('data_karyawan_kompetensi/<int:pk>', DataKompetensiKaryawanDetailView.as_view()),
    path('data_guru_anak', DataAnakGuruListView.as_view()),
    path('data_guru_anak/<int:pk>', DataAnakGuruDetailView.as_view()),
    path('data_guru_beasiswa', DataBeasiswaGuruListView.as_view()),
    path('data_guru_beasiswa/<int:pk>', DataBeasiswaGuruDetailView.as_view()),
    path('data_guru_buku', DataBukuGuruListView.as_view()),
    path('data_guru_buku/<int:pk>', DataBukuGuruDetailView.as_view()),
    path('data_guru_diklat', DataDiklatGuruListView.as_view()),
    path('data_guru_diklat/<int:pk>', DataDiklatGuruDetailView.as_view()),
    path('data_guru_karya_tulis', DataKaryaTulisGuruListView.as_view()),
    path('data_guru_karya_tulis/<int:pk>', DataKaryaTulisGuruDetailView.as_view()),
    path('data_guru_kesejahteraan', DataKesejahteraanGuruListView.as_view()),
    path('data_guru_kesejahteraan/<int:pk>', DataKesejahteraanGuruDetailView.as_view()),
    path('data_guru_tunjangan', DataTunjanganGuruListView.as_view()),
    path('data_guru_tunjangan/<int:pk>', DataTunjanganGuruDetailView.as_view()),
    path('data_guru_tugas_tambahan', DataTugasTambahanGuruListView.as_view()),
    path('data_guru_tugas_tambahan/<int:pk>', DataTugasTambahanGuruDetailView.as_view()),
    path('data_guru_penghargaan', DataPenghargaanGuruListView.as_view()),
    path('data_guru_penghargaan/<int:pk>', DataPenghargaanGuruDetailView.as_view()),
    path('data_guru_nilai_tes', DataNilaiTesGuruListView.as_view()),
    path('data_guru_nilai_tes/<int:pk>', DataNilaiTesGuruDetailView.as_view()),
    path('data_guru_riwayat_gaji_berkala', DataRiwayatGajiBerkalaGuruListView.as_view()),
    path('data_guru_riwayat_gaji_berkala/<int:pk>', DataRiwayatGajiBerkalaGuruDetailView.as_view()),
    path('data_guru_riwayat_jabatan_struktural', DataRiwayatJabatanStrukturalGuruListView.as_view()),
    path('data_guru_riwayat_jabatan_struktural/<int:pk>', DataRiwayatJabatanStrukturalGuruDetailView.as_view()),
    path('data_guru_riwayat_kepangkatan', DataRiwayatKepangkatanGuruListView.as_view()),
    path('data_guru_riwayat_kepangkatan/<int:pk>', DataRiwayatKepangkatanGuruDetailView.as_view()),
    path('data_guru_riwayat_pendidikan_formal', DataRiwayatPendidikanFormalGuruListView.as_view()),
    path('data_guru_riwayat_pendidikan_formal/<int:pk>', DataRiwayatPendidikanFormalGuruDetailView.as_view()),
    path('data_guru_riwayat_sertifikasi', DataRiwayatSertifikasiGuruListView.as_view()),
    path('data_guru_riwayat_sertifikasi/<int:pk>', DataRiwayatSertifikasiGuruDetailView.as_view()),
    path('data_guru_riwayat_jabatan_fungsional', DataRiwayatJabatanFungsionalGuruListView.as_view()),
    path('data_guru_riwayat_jabatan_fungsional/<int:pk>', DataRiwayatJabatanFungsionalGuruDetailView.as_view()),
    path('data_guru_riwayat_karir', DataRiwayatKarirGuruListView.as_view()),
    path('data_guru_riwayat_karir/<int:pk>', DataRiwayatKarirGuruDetailView.as_view()),

]