# Generated by Django 4.0 on 2022-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiKeluar',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_SISWA', models.CharField(max_length=255)),
                ('KELAS', models.CharField(max_length=255)),
                ('NO_INDUK', models.CharField(max_length=255)),
                ('PINDAH_KE', models.CharField(max_length=255)),
                ('TANGGAL_SURAT', models.DateField()),
                ('NO_SURAT', models.CharField(max_length=255)),
                ('BULAN', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('Semester', 'Semester'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=255)),
                ('TAHUN', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mutasi KELUAR',
            },
        ),
        migrations.CreateModel(
            name='MutasiMasuk',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_SISWA', models.CharField(max_length=255)),
                ('ASAL_SEKOLAH', models.CharField(max_length=255)),
                ('NO_INDUK_ASAL', models.CharField(max_length=255)),
                ('ALAMAT', models.CharField(max_length=255)),
                ('KELAS', models.CharField(max_length=255)),
                ('NO_INDUK_BARU', models.CharField(max_length=255)),
                ('TANGGAL_SURAT', models.DateField(max_length=255)),
                ('NO_SURAT', models.CharField(max_length=255)),
                ('BULAN', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('Semester', 'Semester'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=255)),
                ('TAHUN', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mutasi Masuk',
            },
        ),
    ]
