# Generated by Django 4.0 on 2022-03-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutasikeluar',
            options={'verbose_name_plural': 'Mutasi Keluar'},
        ),
    ]
