# Generated by Django 4.0 on 2022-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinduk',
            name='TANGGAL_DITERIMA',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bukuinduk',
            name='TANGGAL_IJAZAH_S',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bukuinduk',
            name='TANGGAL_NO_IJAZAH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bukuinduk',
            name='TANGGAL_NO_SKHUN',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bukuinduk',
            name='TANGGAL_SKHUN_S',
            field=models.DateField(blank=True, null=True),
        ),
    ]
