# Generated by Django 4.0 on 2022-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0002_alter_bukuinduk_tanggal_diterima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinduk',
            name='TANGGAL_MENINGGALKAN_SEKOLAH',
            field=models.DateField(blank=True, null=True),
        ),
    ]
