# Generated by Django 4.0 on 2022-05-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BukuTamu',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=255)),
                ('INSTANSI_ASAL', models.CharField(max_length=255)),
                ('ALAMAT', models.CharField(max_length=255)),
                ('NO_HP', models.CharField(max_length=255)),
                ('HARI', models.CharField(max_length=255)),
                ('TANGGAL', models.DateField()),
                ('JAM', models.TimeField()),
                ('KEPERLUAN', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Buku Tamu',
            },
        ),
        migrations.CreateModel(
            name='LogUKSSiswa',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS_PTK', models.CharField(default='Siswa', max_length=255)),
                ('NAMA', models.CharField(max_length=255)),
                ('KELAS', models.CharField(max_length=255)),
                ('NISN', models.CharField(max_length=255)),
                ('TANGGAL', models.DateField()),
                ('JENIS_PEMERIKSAAN', models.CharField(max_length=255)),
                ('OBAT_DIBERIKAN', models.CharField(max_length=255)),
                ('TINDAK_LANJUT', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Log UKS Siswa',
            },
        ),
        migrations.CreateModel(
            name='LogUKSTendik',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS_PTK', models.CharField(choices=[('Guru Tidak Tetap', 'Guru Tidak Tetap'), ('Aparatur Sipil Negara', 'Aparatur Sipil Negara'), ('Pegawai Tidak Tetap', 'Pegawai Tidak Tetap'), ('Guru', 'ASN')], max_length=255)),
                ('NAMA', models.CharField(max_length=255)),
                ('TANGGAL', models.DateField()),
                ('JENIS_PEMERIKSAAN', models.CharField(max_length=255)),
                ('OBAT_DIBERIKAN', models.CharField(max_length=255)),
                ('TINDAK_LANJUT', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Log UKS Tendik',
            },
        ),
    ]
