# Generated by Django 4.0 on 2022-03-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubungan_masyarakat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bukutamu',
            options={'verbose_name_plural': 'Buku Tamu'},
        ),
        migrations.AlterModelOptions(
            name='logukssiswa',
            options={'ordering': ['-TANGGAL'], 'verbose_name_plural': 'Log UKS Siswa'},
        ),
        migrations.AlterModelOptions(
            name='logukstendik',
            options={'verbose_name_plural': 'Log UKS Tendik'},
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='HARI',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jum`at', 'Jum`at'), ('Sabtu', 'Sabtu')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='KEPERLUAN',
            field=models.CharField(max_length=255),
        ),
    ]
