# Generated by Django 4.0 on 2022-03-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubungan_masyarakat', '0002_alter_bukutamu_options_alter_logukssiswa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logukssiswa',
            options={'verbose_name_plural': 'Log UKS Siswa'},
        ),
    ]
