# Generated by Django 4.0 on 2022-05-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaringanKerja',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE_MOU', models.FileField(max_length=255, upload_to='JaringanKerja/MOU')),
                ('FILE_DOKUMENTASI', models.FileField(max_length=255, upload_to='JaringanKerja/Dokumentasi')),
            ],
            options={
                'verbose_name_plural': 'Jaringan Kerja',
            },
        ),
        migrations.CreateModel(
            name='KaryaInovatif',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_INOVATOR', models.CharField(max_length=255)),
                ('NAMA_KARYA_INOVATIF', models.CharField(max_length=255)),
                ('JENIS', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='KaryaInovatif')),
                ('KETERANGAN', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Karya Inovatif',
            },
        ),
        migrations.CreateModel(
            name='KegiatanKader',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='KegiatanKader')),
            ],
            options={
                'verbose_name_plural': 'Kegiatan Kader',
            },
        ),
        migrations.CreateModel(
            name='Konservasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('KATEGORI', models.CharField(choices=[('Energi', 'Energi'), ('Air', 'Air')], max_length=255)),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='Konservasi')),
            ],
            options={
                'verbose_name_plural': 'Konservasi',
            },
        ),
        migrations.CreateModel(
            name='PembibitanPohon',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='PembibitanPohon')),
            ],
            options={
                'verbose_name_plural': 'Pembibitan Pohon',
            },
        ),
        migrations.CreateModel(
            name='PemeliharaanPohon',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='PemeliharaanPohon')),
            ],
            options={
                'verbose_name_plural': 'Pemeliharaan Pohon',
            },
        ),
        migrations.CreateModel(
            name='PemeliharaanSampah',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.TextField()),
                ('FILE', models.FileField(max_length=255, upload_to='PemeliharaanSampah')),
            ],
            options={
                'verbose_name_plural': 'Pemeliharaan Sampah',
            },
        ),
        migrations.CreateModel(
            name='PenanamanPohon',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('JUMLAH', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='PenanamanPohon')),
            ],
            options={
                'verbose_name_plural': 'Penanaman Pohon',
            },
        ),
        migrations.CreateModel(
            name='PenerapanPRLH',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('PESERTA', models.CharField(max_length=255)),
                ('KETERANGAN', models.TextField()),
                ('FILE', models.FileField(max_length=255, upload_to='PenerapanPRLH')),
            ],
            options={
                'verbose_name_plural': 'Penerapan PRLH',
            },
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('JENIS_MEDIA', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='Publikasi')),
            ],
            options={
                'verbose_name_plural': 'Publikasi',
            },
        ),
        migrations.CreateModel(
            name='ReuseReduceRecycle',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('JENIS_KEGIATAN', models.CharField(choices=[('Reuse', 'Reuse'), ('Reduce', 'Reduce'), ('Recycle', 'Recycle')], max_length=255)),
                ('PIHAK_TERLIBAT', models.CharField(max_length=255)),
                ('KETERANGAN', models.TextField()),
                ('FILE', models.FileField(max_length=255, upload_to='ReuseReduceRecycle')),
            ],
            options={
                'verbose_name_plural': 'Reuse Reduce Recycle',
            },
        ),
        migrations.CreateModel(
            name='SanitasiDrainase',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('UNSUR_TERLIBAT', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to='SanitasiDrainase')),
            ],
            options={
                'verbose_name_plural': 'Sanitasi Drainase',
            },
        ),
        migrations.CreateModel(
            name='TabunganSampah',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('KATEGORI', models.CharField(choices=[('Basah', 'Basah'), ('Kering', 'Kering')], max_length=255)),
                ('TANGGAL', models.DateField()),
                ('JUMLAH', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tabungan Sampah',
            },
        ),
        migrations.CreateModel(
            name='DaftarKader',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
            options={
                'verbose_name_plural': 'Daftar Kader',
            },
        ),
        migrations.CreateModel(
            name='TabunganSampahProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Jumlah Tabungan Sampah',
                'ordering': ['TANGGAL'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('adiwiyata.tabungansampah',),
        ),
    ]
