# Generated by Django 4.0 on 2022-03-24 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataprofil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaringanKerja',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='KaryaInovatif',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_INOVATOR', models.CharField(max_length=255)),
                ('NAMA_KARYA_INOVATIF', models.CharField(max_length=255)),
                ('JENIS', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='KegiatanKader',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Konservasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('KATEGORI', models.CharField(choices=[('Energi', 'Energi'), ('Air', 'Air')], max_length=255)),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='PembibitanPohon',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='PemeliharaanPohon',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='PemeliharaanSampah',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('KETERANGAN', models.TextField()),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='PenanamanPohon',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('JUMLAH', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='PenerapanPRLH',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('PESERTA', models.CharField(max_length=255)),
                ('KETERANGAN', models.TextField()),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('JENIS_MEDIA', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='ReuseReduceRecycle',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('JENIS_KEGIATAN', models.CharField(choices=[('Reuse', 'Reuse'), ('Reduce', 'Reduce'), ('Recycle', 'Recycle')], max_length=255)),
                ('PIHAK_TERLIBAT', models.CharField(max_length=255)),
                ('KETERANGAN', models.TextField()),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='SanitasiDrainase',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('NAMA_KEGIATAN', models.CharField(max_length=255)),
                ('UNSUR_TERLIBAT', models.CharField(max_length=255)),
                ('KETERANGAN', models.CharField(max_length=255)),
                ('FILE', models.FileField(max_length=255, upload_to=' ')),
            ],
        ),
        migrations.CreateModel(
            name='TabunganSampah',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TANGGAL', models.DateField()),
                ('JUMLAH_PERTANGGAL', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DaftarKader',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
            ],
        ),
    ]
