# Generated by Django 4.0 on 2022-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiwiyata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jaringankerja',
            name='FILE_DOKUMENTASI',
        ),
        migrations.RemoveField(
            model_name='jaringankerja',
            name='FILE_MOU',
        ),
        migrations.AddField(
            model_name='jaringankerja',
            name='FILE',
            field=models.FileField(default='', max_length=255, upload_to='JaringanKerja'),
            preserve_default=False,
        ),
    ]
