# Generated by Django 4.0 on 2022-03-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiwiyata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaringankerja',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='JaringanKerja'),
        ),
        migrations.AlterField(
            model_name='karyainovatif',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='KaryaInovatif'),
        ),
        migrations.AlterField(
            model_name='kegiatankader',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='KegiatanKader'),
        ),
        migrations.AlterField(
            model_name='konservasi',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='Konservasi'),
        ),
        migrations.AlterField(
            model_name='pembibitanpohon',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='PembibitanPohon'),
        ),
        migrations.AlterField(
            model_name='pemeliharaanpohon',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='PemeliharaanPohon'),
        ),
        migrations.AlterField(
            model_name='pemeliharaansampah',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='PemeliharaanSampah'),
        ),
        migrations.AlterField(
            model_name='penanamanpohon',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='PenanamanPohon'),
        ),
        migrations.AlterField(
            model_name='penerapanprlh',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='PenerapanPRLH'),
        ),
        migrations.AlterField(
            model_name='publikasi',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='Publikasi'),
        ),
        migrations.AlterField(
            model_name='reusereducerecycle',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='ReuseReduceRecycle'),
        ),
        migrations.AlterField(
            model_name='sanitasidrainase',
            name='FILE',
            field=models.FileField(max_length=255, upload_to='SanitasiDrainase'),
        ),
    ]
