# Generated by Django 4.0 on 2022-03-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiwiyata', '0003_tabungansampahproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabungansampahproxy',
            options={'ordering': ['TANGGAL'], 'verbose_name_plural': 'Jumlah Tabungan Sampah'},
        ),
        migrations.AddField(
            model_name='tabungansampah',
            name='KATEGORI',
            field=models.CharField(choices=[('Basah', 'Basah'), ('Kering', 'Kering')], default='Basah', max_length=255),
            preserve_default=False,
        ),
    ]
