# Generated by Django 4.0 on 2022-03-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adiwiyata', '0004_alter_tabungansampahproxy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftarkader',
            options={'verbose_name_plural': 'Daftar Kader'},
        ),
        migrations.AlterModelOptions(
            name='jaringankerja',
            options={'verbose_name_plural': 'Jaringan Kerja'},
        ),
        migrations.AlterModelOptions(
            name='karyainovatif',
            options={'verbose_name_plural': 'Karya Inovatif'},
        ),
        migrations.AlterModelOptions(
            name='kegiatankader',
            options={'verbose_name_plural': 'Kegiatan Kader'},
        ),
        migrations.AlterModelOptions(
            name='konservasi',
            options={'verbose_name_plural': 'Konservasi'},
        ),
        migrations.AlterModelOptions(
            name='pembibitanpohon',
            options={'verbose_name_plural': 'Pembibitan Pohon'},
        ),
        migrations.AlterModelOptions(
            name='pemeliharaanpohon',
            options={'verbose_name_plural': 'Pemeliharaan Pohon'},
        ),
        migrations.AlterModelOptions(
            name='pemeliharaansampah',
            options={'verbose_name_plural': 'Pemeliharaan Sampah'},
        ),
        migrations.AlterModelOptions(
            name='penanamanpohon',
            options={'verbose_name_plural': 'Penanaman Pohon'},
        ),
        migrations.AlterModelOptions(
            name='penerapanprlh',
            options={'verbose_name_plural': 'Penerapan PRLH'},
        ),
        migrations.AlterModelOptions(
            name='publikasi',
            options={'verbose_name_plural': 'Publikasi'},
        ),
        migrations.AlterModelOptions(
            name='reusereducerecycle',
            options={'verbose_name_plural': 'Reuse Reduce Recycle'},
        ),
        migrations.AlterModelOptions(
            name='sanitasidrainase',
            options={'verbose_name_plural': 'Sanitasi Drainase'},
        ),
        migrations.AlterModelOptions(
            name='tabungansampah',
            options={'verbose_name_plural': 'Tabungan Sampah'},
        ),
    ]
