# Generated by Django 4.0 on 2022-03-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiwiyata', '0005_alter_daftarkader_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyainovatif',
            name='KETERANGAN',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
