# Generated by Django 4.0 on 2021-12-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiswa',
            fields=[
                ('NISN', models.BigIntegerField(max_length=225, primary_key=True, serialize=False)),
                ('NAMA', models.CharField(max_length=225)),
                ('NIPD', models.IntegerField(max_length=225)),
                ('JENIS_KELAMIN', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=20)),
                ('TEMPAT_LAHIR', models.CharField(max_length=225)),
                ('TANGGAL_LAHIR', models.DateField()),
                ('NIK', models.BigIntegerField(max_length=225)),
                ('AGAMA', models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Budha', 'Budha'), ('Hindu', 'Hindu'), ('Konghuchu', 'Konghuchu')], max_length=20)),
                ('ALAMAT', models.CharField(max_length=225)),
                ('RT', models.BigIntegerField(max_length=3)),
                ('RW', models.BigIntegerField(max_length=3)),
                ('DUSUN', models.CharField(max_length=225)),
                ('KELURAHAN', models.CharField(max_length=225)),
                ('KECAMATAN', models.CharField(max_length=225)),
                ('KODE_POS', models.BigIntegerField(max_length=225)),
                ('JENIS_TINGGAL', models.CharField(choices=[('Bersama Orang Tua', 'Bersama Orang Tua'), ('Bersama Wali', 'Bersama Wali'), ('Mandiri', 'Mandiri')], max_length=225)),
                ('TELEPON', models.BigIntegerField(blank=True, max_length=225)),
                ('HP', models.BigIntegerField(blank=True, max_length=225)),
                ('EMAIL', models.CharField(blank=True, max_length=225)),
                ('SKHUN', models.CharField(blank=True, max_length=225)),
                ('PENERIMA_KPS', models.CharField(choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5)),
                ('NO_KPS', models.BigIntegerField(blank=True, max_length=225)),
                ('ROMBEL_SAAT_INI', models.CharField(blank=True, max_length=225)),
                ('NO_PESERTA_UJIAN_NASIONAL', models.CharField(blank=True, max_length=225)),
                ('NO_SERI_IJAZAH', models.CharField(blank=True, max_length=225)),
                ('PENERIMA_KIP', models.CharField(choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5)),
                ('NO_KKS', models.BigIntegerField(blank=True, max_length=225)),
                ('NO_REGRISTASI_AKTA_LAHIR', models.CharField(blank=True, max_length=225)),
                ('BANK', models.CharField(blank=True, max_length=225)),
                ('NO_REKENING_BANK', models.CharField(blank=True, max_length=225)),
                ('REKENING_ATAS_NAMA', models.CharField(blank=True, max_length=225)),
                ('LAYAK_PIP', models.CharField(choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5)),
                ('KEBUTUHAN_KHUSUS', models.CharField(blank=True, max_length=225)),
                ('ANAK_KE', models.CharField(blank=True, max_length=225)),
                ('LINTANG', models.CharField(blank=True, max_length=225)),
                ('BUJUR', models.CharField(blank=True, max_length=225)),
                ('NO_KK', models.BigIntegerField(blank=True, max_length=225)),
                ('BERAT_BADAN', models.IntegerField(blank=True, max_length=3)),
                ('TINGGI_BADAN', models.IntegerField(blank=True, max_length=3)),
                ('LINGKAR_KEPALA', models.IntegerField(blank=True, max_length=5)),
                ('JUMLAH_SAUDARA_KANDUNG', models.IntegerField(blank=True, max_length=5)),
                ('JARAK_RUMAH_KESEKOLAH_KM', models.IntegerField(blank=True, max_length=225)),
            ],
        ),
    ]
