# Generated by Django 4.0 on 2022-03-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorangtua',
            name='AGAMA_AYAH',
            field=models.CharField(max_length=255, default=''),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='AGAMA_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='AGAMA_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='ALAMAT_AYAH',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='ALAMAT_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='ALAMAT_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='HP_AYAH',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='HP_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='HP_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='KEWARGANEGARAAN_AYAH',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='KEWARGANEGARAAN_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='KEWARGANEGARAAN_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='MASIH_HIDUP_AYAH',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='MASIH_HIDUP_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='MASIH_HIDUP_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='PENGELUARAN_PER_BULAN_AYAH',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='PENGELUARAN_PER_BULAN_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='PENGELUARAN_PER_BULAN_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TELEPON_AYAH',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TELEPON_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TELEPON_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TEMPAT_LAHIR_IBU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TEMPAT_LAHIR_WALI',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
