# Generated by Django 4.0 on 2022-03-04 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanakguru',
            name='TANGGAL_LAHIR',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataanakkaryawan',
            name='TANGGAL_LAHIR',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='TANGGAL_LAHIR',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='TGL_SURAT',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='datakaryawan',
            name='TANGGAL_LAHIR',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datakaryawan',
            name='TGL_SURAT',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TAHUN_LAHIR_AYAH',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TAHUN_LAHIR_IBU',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='TAHUN_LAHIR_WALI',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datariwayatgajiberkalaguru',
            name='TANGGAL_SK',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datariwayatgajiberkalakaryawan',
            name='TANGGAL_SK',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datariwayatkarirguru',
            name='TGL_SK_KERJA',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datariwayatkarirkaryawan',
            name='TGL_SK_KERJA',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datariwayatkepangkatanguru',
            name='TANGGAL_SK',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datariwayatkepangkatankaryawan',
            name='TANGGAL_SK',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='TANGGAL_LAHIR',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
