# Generated by Django 4.0 on 2021-12-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='HP',
            field=models.BigIntegerField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='TELEPON',
            field=models.BigIntegerField(blank=True, max_length=225, null=True),
        ),
    ]
