# Generated by Django 4.0 on 2022-03-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0002_alter_dataorangtua_agama_ayah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorangtua',
            name='AGAMA_AYAH',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
