# Generated by Django 4.0 on 2022-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0002_alter_dataanakguru_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasiswa',
            name='STATUS_LULUS',
            field=models.CharField(blank=True, choices=[('Lulus', 'Lulus'), ('Belum Lulus', 'Belum Lulus')], max_length=255),
        ),
    ]
