# Generated by Django 4.0 on 2021-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0003_alter_datasiswa_berat_badan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasiswa',
            options={'verbose_name_plural': 'Data Siswa'},
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='BERAT_BADAN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='HP',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='JARAK_RUMAH_KESEKOLAH_KM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='JUMLAH_SAUDARA_KANDUNG',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='KODE_POS',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='LINGKAR_KEPALA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='NIK',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='NIPD',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='NISN',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='NO_KK',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='NO_KKS',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='NO_KPS',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='RT',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='RW',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='TELEPON',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='TINGGI_BADAN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DataOrangTua',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NAMA_AYAH', models.CharField(max_length=225)),
                ('TAHUN_LAHIR_AYAH', models.DateField()),
                ('JENJANG_PENDIDIKAN_AYAH', models.CharField(choices=[('Tidak Bersekolah', 'Tidak Bersekolah'), ('SD/Sederajat', 'SD/Sederajat'), ('SMP/Sederajat', 'SMP/Sederajat'), ('SMA/Sederajat', 'SMA/Sederajat'), ('D1', 'D4'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('PEKERJAAN_AYAH', models.CharField(max_length=225)),
                ('PENGHASILAN_AYAH', models.CharField(choices=[('Kurang dari Rp 500.000;', 'Kurang dari Rp 500.000;'), ('Rp 500.000;- RP 1.500.000;', 'Rp 500.000;- RP 1.500.000;'), ('Rp 1.500.000;- Rp 3.500.000;', 'Rp 1.500.000;- Rp 3.500.000;'), ('Rp 3.500.000;- Rp 5.000.000;', 'Rp 3.500.000;- Rp 5.000.000;'), ('Rp 5.000.000; Ke Atas', 'Rp 5.000.000; Ke Atas')], max_length=225)),
                ('NIK_IBU', models.BigIntegerField()),
                ('NAMA_IBU', models.CharField(max_length=225)),
                ('TAHUN_LAHIR_IBU', models.DateField()),
                ('JENJANG_PENDIDIKAN_IBU', models.CharField(choices=[('Tidak Bersekolah', 'Tidak Bersekolah'), ('SD/Sederajat', 'SD/Sederajat'), ('SMP/Sederajat', 'SMP/Sederajat'), ('SMA/Sederajat', 'SMA/Sederajat'), ('D1', 'D4'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('PEKERJAAN_IBU', models.CharField(max_length=225)),
                ('PENGHASILAN_IBU', models.CharField(choices=[('Kurang dari Rp 500.000;', 'Kurang dari Rp 500.000;'), ('Rp 500.000;- RP 1.500.000;', 'Rp 500.000;- RP 1.500.000;'), ('Rp 1.500.000;- Rp 3.500.000;', 'Rp 1.500.000;- Rp 3.500.000;'), ('Rp 3.500.000;- Rp 5.000.000;', 'Rp 3.500.000;- Rp 5.000.000;'), ('Rp 5.000.000; Ke Atas', 'Rp 5.000.000; Ke Atas')], max_length=225)),
                ('NIK_WALI', models.BigIntegerField()),
                ('NAMA_WALI', models.CharField(max_length=225)),
                ('TAHUN_LAHIR_WALI', models.DateField()),
                ('JENJANG_PENDIDIKAN_WALI', models.CharField(choices=[('Tidak Bersekolah', 'Tidak Bersekolah'), ('SD/Sederajat', 'SD/Sederajat'), ('SMP/Sederajat', 'SMP/Sederajat'), ('SMA/Sederajat', 'SMA/Sederajat'), ('D1', 'D4'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('PEKERJAAN_WALI', models.CharField(max_length=225)),
                ('PENGHASILAN_WALI', models.CharField(choices=[('Kurang dari Rp 500.000;', 'Kurang dari Rp 500.000;'), ('Rp 500.000;- RP 1.500.000;', 'Rp 500.000;- RP 1.500.000;'), ('Rp 1.500.000;- Rp 3.500.000;', 'Rp 1.500.000;- Rp 3.500.000;'), ('Rp 3.500.000;- Rp 5.000.000;', 'Rp 3.500.000;- Rp 5.000.000;'), ('Rp 5.000.000; Ke Atas', 'Rp 5.000.000; Ke Atas')], max_length=225)),
                ('DATA_ANAK', models.ManyToManyField(to='dataprofil.DataSiswa', verbose_name='Daftar Anak')),
            ],
            options={
                'verbose_name_plural': 'Data Orangtua dan Wali',
            },
        ),
    ]
