# Generated by Django 4.0 on 2022-03-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0003_alter_dataorangtua_agama_ayah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorangtua',
            name='AGAMA_AYAH',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Budha', 'Budha'), ('Hindu', 'Hindu'), ('Konghuchu', 'Konghuchu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='AGAMA_IBU',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Budha', 'Budha'), ('Hindu', 'Hindu'), ('Konghuchu', 'Konghuchu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='AGAMA_WALI',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Budha', 'Budha'), ('Hindu', 'Hindu'), ('Konghuchu', 'Konghuchu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='MASIH_HIDUP_AYAH',
            field=models.CharField(choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='MASIH_HIDUP_IBU',
            field=models.CharField(choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataorangtua',
            name='MASIH_HIDUP_WALI',
            field=models.CharField(choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=255, null=True),
        ),
    ]
