# Generated by Django 4.0 on 2022-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0003_datasiswa_status_lulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='STATUS_LULUS',
            field=models.CharField(blank=True, choices=[('Lulus', 'Lulus'), ('Belum Lulus', 'Belum Lulus')], default='Belum Lulus', max_length=255),
        ),
    ]
