# Generated by Django 4.0 on 2021-12-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0004_alter_datasiswa_options_alter_datasiswa_berat_badan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorangtua',
            name='DATA_ANAK',
            field=models.ManyToManyField(to='dataprofil.DataSiswa', verbose_name=''),
        ),
    ]
