# Generated by Django 4.0 on 2022-03-03 07:50

import adistetsa.custom_function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0004_remove_dataorangtua_pekerjaan_wali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataorangtua',
            name='PEKERJAAN_WALI',
            field=models.CharField(blank=True, max_length=225, validators=[adistetsa.custom_function.cek_huruf_besar_awal_kalimat]),
        ),
        migrations.AlterField(
            model_name='dataguru',
            name='JENIS_PTK',
            field=models.CharField(blank=True, choices=[('Guru Mapel', 'Guru Mapel'), ('Guru Kelas', 'Guru Kelas'), ('Guru BK', 'Guru BK'), ('Guru Inklusi', 'Guru Inklusi'), ('Tenaga Administrasi', 'Tenaga Administrasi'), ('Guru TIK', 'Guru TIK'), ('Laboran', 'Laboran'), ('Tenaga Perpustakaan', 'Tenaga Perpustakaan'), ('Tukang Kebun', 'Tukang Kebun'), ('Penjaga Sekolah', 'Penjaga Sekolah'), ('Petugas Keamanan', 'Petugas Keamanan'), ('Pesuruh/Office Boy', 'Pesuruh/Office Boy'), ('Kepala Sekolah', 'Kepala Sekolah')], max_length=225),
        ),
    ]
