# Generated by Django 4.0 on 2021-12-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0005_alter_dataorangtua_data_anak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorangtua',
            name='DATA_ANAK',
            field=models.ManyToManyField(to='dataprofil.DataSiswa', verbose_name='DAFTAR ANAK'),
        ),
    ]
