# Generated by Django 4.0 on 2021-12-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0007_alter_dataorangtua_jenjang_pendidikan_ayah_and_more'),
        ('dataprofil', '0007_dataanakpegawai_databeasiswapegawai_databukupegawai_and_more'),
    ]

    operations = [
    ]
