# Generated by Django 4.0 on 2021-12-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dataprofil', '0008_merge_20211228_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datakompetensipegawai',
            options={'verbose_name_plural': 'Data Kompetensi Pegawai'},
        ),
        migrations.RenameField(
            model_name='datapegawai',
            old_name='DATA_BEASISWA_BEGAWAI',
            new_name='DATA_BEASISWA_PEGAWAI',
        ),
        migrations.RenameField(
            model_name='datapegawai',
            old_name='DATA_DATA_PENDIDIKAN_NORMAL_PEGAWAI',
            new_name='DATA_PENDIDIKAN_NORMAL_PEGAWAI',
        ),
        migrations.CreateModel(
            name='DataSiswaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NISN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
