# Generated by Django 4.0 on 2021-12-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0009_alter_datakompetensipegawai_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSiswaUser',
        ),
    ]
