# Generated by Django 4.0 on 2021-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0011_alter_datapegawai_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapegawai',
            old_name='NAMA_lENGKAP',
            new_name='NAMA_LENGKAP',
        ),
        migrations.AlterField(
            model_name='datariwayatkarirgurupegawai',
            name='TTD_SK_KERJA',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
