# Generated by Django 4.0 on 2021-12-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0012_dataguru_datakaryawan_and_more'),
        ('dataprofil', '0012_rename_nama_lengkap_datapegawai_nama_lengkap_and_more'),
    ]

    operations = [
    ]
