# Generated by Django 4.0 on 2021-12-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0013_merge_20211229_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnakGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(blank=True, max_length=225)),
                ('JENJANG', models.CharField(blank=True, max_length=225)),
                ('NISN', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('JENIS_KELAMIN', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=20)),
                ('TEMPAT_LAHIR', models.CharField(blank=True, max_length=225)),
                ('TANGGAL_LAHIR', models.DateField(blank=True)),
                ('TAHUN_MASUK', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Anak Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataAnakKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(blank=True, max_length=225)),
                ('JENJANG', models.CharField(blank=True, max_length=225)),
                ('NISN', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('JENIS_KELAMIN', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=20)),
                ('TEMPAT_LAHIR', models.CharField(blank=True, max_length=225)),
                ('TANGGAL_LAHIR', models.DateField(blank=True)),
                ('TAHUN_MASUK', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Anak Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataBeasiswaGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('DARI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('SAMPAI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('MASIH_MENERIMA', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Beasiswa Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataBeasiswaKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('DARI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('SAMPAI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('MASIH_MENERIMA', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Beasiswa Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataBukuGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JUDUL_BUKU', models.CharField(blank=True, max_length=225)),
                ('TAHUN_BUKU', models.CharField(blank=True, max_length=225)),
                ('PENERBIT_BUKU', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Buku Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataBukuKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JUDUL_BUKU', models.CharField(blank=True, max_length=225)),
                ('TAHUN_BUKU', models.CharField(blank=True, max_length=225)),
                ('PENERBIT_BUKU', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Buku Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataDiklatGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS_DIKLAT', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('PERAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Diklat Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataDiklatKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS_DIKLAT', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('PERAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Diklat Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataKaryaTulisGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JUDUL', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('PUBLIKASI', models.CharField(blank=True, max_length=225)),
                ('KETERANGAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Karya Tulis Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataKaryaTulisKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JUDUL', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('PUBLIKASI', models.CharField(blank=True, max_length=225)),
                ('KETERANGAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Karya Tulis Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataKesejahteraanGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('DARI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('SAMPAI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('STATUS', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Kesejahteraan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataKesejahteraanKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('DARI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('SAMPAI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('STATUS', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Kesejahteraan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataKompetensiGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BIDANG_STUDI', models.CharField(blank=True, max_length=225)),
                ('URUTAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Kompetensi Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataKompetensiKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BIDANG_STUDI', models.CharField(blank=True, max_length=225)),
                ('URUTAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Kompetensi Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataNilaiTesGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('SKOR', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Nilai Test Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataNilaiTesKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('PENYELENGGARA', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('SKOR', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Nilai Test Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataPenghargaanGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TINGKAT_PERNGHARGAAN', models.CharField(blank=True, max_length=225)),
                ('JENIS_PENGHARGAAN', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('INSTANSI', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Penghargaan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataPenghargaanKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TINGKAT_PERNGHARGAAN', models.CharField(blank=True, max_length=225)),
                ('JENIS_PENGHARGAAN', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('TAHUN', models.CharField(blank=True, max_length=225)),
                ('INSTANSI', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Penghargaan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatGajiBerkalaGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PANGKAT_GOLONGAN', models.CharField(blank=True, max_length=225)),
                ('NO_SK', models.CharField(blank=True, max_length=225)),
                ('TANGGAL_SK', models.DateField()),
                ('TMT_KGB', models.CharField(blank=True, max_length=225)),
                ('TAHUN_MK', models.CharField(blank=True, max_length=225)),
                ('BULAN_MK', models.CharField(blank=True, max_length=225)),
                ('GAJI_POKOK', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Gaji Berkala Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatGajiBerkalaKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PANGKAT_GOLONGAN', models.CharField(blank=True, max_length=225)),
                ('NO_SK', models.CharField(blank=True, max_length=225)),
                ('TANGGAL_SK', models.DateField()),
                ('TMT_KGB', models.CharField(blank=True, max_length=225)),
                ('TAHUN_MK', models.CharField(blank=True, max_length=225)),
                ('BULAN_MK', models.CharField(blank=True, max_length=225)),
                ('GAJI_POKOK', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Gaji Berkala Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatJabatanFungsionalGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JABATAN_FUNGSIONAL', models.CharField(blank=True, max_length=225)),
                ('SK_JABATAN_FUNGSIONAL', models.CharField(blank=True, max_length=225)),
                ('TMT_JABATAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Jabatan Fungsional Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatJabatanFungsionalKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JABATAN_FUNGSIONAL', models.CharField(blank=True, max_length=225)),
                ('SK_JABATAN_FUNGSIONAL', models.CharField(blank=True, max_length=225)),
                ('TMT_JABATAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Jabatan Fungsional Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatJabatanStrukturalGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JABATAN_PTK', models.CharField(blank=True, max_length=225)),
                ('SK_STRUKTURAL', models.CharField(blank=True, max_length=225)),
                ('TMT_JABATAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Jabatan Struktural Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatJabatanStrukturalKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JABATAN_PTK', models.CharField(blank=True, max_length=225)),
                ('SK_STRUKTURAL', models.CharField(blank=True, max_length=225)),
                ('TMT_JABATAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Jabatan Struktural Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatKarirGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENJANG', models.CharField(blank=True, max_length=225)),
                ('JENIS_LEMBAGA', models.CharField(blank=True, max_length=225)),
                ('STS_KEPEGAWAIAN', models.CharField(blank=True, max_length=225)),
                ('JENIS_PTK', models.CharField(blank=True, max_length=225)),
                ('LEMBAGA', models.CharField(blank=True, max_length=225)),
                ('NO_SK_KERJA', models.CharField(blank=True, max_length=225)),
                ('TGL_SK_KERJA', models.DateField()),
                ('TMT_KERJA', models.CharField(blank=True, max_length=225)),
                ('TST_KERJA', models.CharField(blank=True, max_length=225)),
                ('TEMPAT_KERJA', models.CharField(blank=True, max_length=225)),
                ('TTD_SK_KERJA', models.CharField(blank=True, max_length=225)),
                ('MAPEL_DIAJARKAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Karir Guru Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatKarirKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENJANG', models.CharField(blank=True, max_length=225)),
                ('JENIS_LEMBAGA', models.CharField(blank=True, max_length=225)),
                ('STS_KEPEGAWAIAN', models.CharField(blank=True, max_length=225)),
                ('JENIS_PTK', models.CharField(blank=True, max_length=225)),
                ('LEMBAGA', models.CharField(blank=True, max_length=225)),
                ('NO_SK_KERJA', models.CharField(blank=True, max_length=225)),
                ('TGL_SK_KERJA', models.DateField()),
                ('TMT_KERJA', models.CharField(blank=True, max_length=225)),
                ('TST_KERJA', models.CharField(blank=True, max_length=225)),
                ('TEMPAT_KERJA', models.CharField(blank=True, max_length=225)),
                ('TTD_SK_KERJA', models.CharField(blank=True, max_length=225)),
                ('MAPEL_DIAJARKAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Karir Guru Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatKepangkatanGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NO_SK', models.CharField(blank=True, max_length=225)),
                ('TANGGAL_SK', models.DateField()),
                ('PANGKAT_GOLONGAN', models.CharField(blank=True, max_length=225)),
                ('MK_TAHUN', models.CharField(blank=True, max_length=225)),
                ('MK_BULAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Kepangkatan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatKepangkatanKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NO_SK', models.CharField(blank=True, max_length=225)),
                ('TANGGAL_SK', models.DateField()),
                ('PANGKAT_GOLONGAN', models.CharField(blank=True, max_length=225)),
                ('MK_TAHUN', models.CharField(blank=True, max_length=225)),
                ('MK_BULAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Kepangkatan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatPendidikanFormalGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BIDANG_STUDI', models.CharField(blank=True, max_length=225)),
                ('JENJANG', models.CharField(blank=True, max_length=225)),
                ('GELAR', models.CharField(blank=True, max_length=225)),
                ('SATUAN', models.CharField(blank=True, max_length=225)),
                ('FAKULTAS', models.CharField(blank=True, max_length=225)),
                ('KEPENDIDIKAN', models.CharField(blank=True, max_length=225)),
                ('TAHUN_MASUK', models.CharField(blank=True, max_length=225)),
                ('TAHUN_LULUS', models.CharField(blank=True, max_length=225)),
                ('NIM', models.CharField(blank=True, max_length=225)),
                ('MASIH', models.CharField(blank=True, max_length=225)),
                ('SMT', models.CharField(blank=True, max_length=225)),
                ('IPK', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Pendidikan Formal Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatPendidikanFormalKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BIDANG_STUDI', models.CharField(blank=True, max_length=225)),
                ('JENJANG', models.CharField(blank=True, max_length=225)),
                ('GELAR', models.CharField(blank=True, max_length=225)),
                ('SATUAN', models.CharField(blank=True, max_length=225)),
                ('FAKULTAS', models.CharField(blank=True, max_length=225)),
                ('KEPENDIDIKAN', models.CharField(blank=True, max_length=225)),
                ('TAHUN_MASUK', models.CharField(blank=True, max_length=225)),
                ('TAHUN_LULUS', models.CharField(blank=True, max_length=225)),
                ('NIM', models.CharField(blank=True, max_length=225)),
                ('MASIH', models.CharField(blank=True, max_length=225)),
                ('SMT', models.CharField(blank=True, max_length=225)),
                ('IPK', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Pendidikan Formal Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatSertifikasiGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS_SERTIFIKASI', models.CharField(blank=True, max_length=225)),
                ('NO_SERTIFIKASI', models.CharField(blank=True, max_length=225)),
                ('TAHUN_SERTIFIKASI', models.CharField(blank=True, max_length=225)),
                ('BIDANG_STUDI', models.CharField(blank=True, max_length=225)),
                ('NO_REGISTRASI', models.CharField(blank=True, max_length=225)),
                ('NO_PESERTA', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Sertifikasi Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataRiwayatSertifikasiKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JENIS_SERTIFIKASI', models.CharField(blank=True, max_length=225)),
                ('NO_SERTIFIKASI', models.CharField(blank=True, max_length=225)),
                ('TAHUN_SERTIFIKASI', models.CharField(blank=True, max_length=225)),
                ('BIDANG_STUDI', models.CharField(blank=True, max_length=225)),
                ('NO_REGISTRASI', models.CharField(blank=True, max_length=225)),
                ('NO_PESERTA', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Riwayat Sertifikasi Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataTugasTambahanGuru',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JABATAN_PTK', models.CharField(blank=True, max_length=225)),
                ('JPM', models.CharField(blank=True, max_length=225)),
                ('NO_SK', models.CharField(blank=True, max_length=225)),
                ('TMT_TAMBAHAN', models.CharField(blank=True, max_length=225)),
                ('TST_TAMBAHAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Tugas Tambahan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataTugasTambahanKaryawan',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('JABATAN_PTK', models.CharField(blank=True, max_length=225)),
                ('JPM', models.CharField(blank=True, max_length=225)),
                ('NO_SK', models.CharField(blank=True, max_length=225)),
                ('TMT_TAMBAHAN', models.CharField(blank=True, max_length=225)),
                ('TST_TAMBAHAN', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Tugas Tambahan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataTunjanganGuru',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('INSTANSI', models.CharField(blank=True, max_length=225)),
                ('SUMBER_DANA', models.CharField(blank=True, max_length=225)),
                ('DARI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('SAMPAI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('NOMINAL', models.CharField(blank=True, max_length=225)),
                ('STATUS', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Tunjangan Pegawai',
            },
        ),
        migrations.CreateModel(
            name='DataTunjanganKaryawan',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('JENIS', models.CharField(blank=True, max_length=225)),
                ('NAMA', models.CharField(blank=True, max_length=225)),
                ('INSTANSI', models.CharField(blank=True, max_length=225)),
                ('SUMBER_DANA', models.CharField(blank=True, max_length=225)),
                ('DARI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('SAMPAI_TAHUN', models.CharField(blank=True, max_length=225)),
                ('NOMINAL', models.CharField(blank=True, max_length=225)),
                ('STATUS', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Data Tunjangan Pegawai',
            },
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_ANAK_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_BEASISWA_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_BUKU_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_DIKLAT_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_KARYA_TULIS_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_KESEJAHTERAAN_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_KOMPETENSI_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_NILAI_TEST_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_PENDIDIKAN_NORMAL_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_PENGHARGAAN_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_RIWAYAT_GAJI_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_RIWAYAT_JABATAN_FUNGSIONAL_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_RIWAYAT_JABATAN_STRUKTURAL_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_RIWAYAT_KARIR_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_RIWAYAT_KEPANGKATAN_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_SERTIFIKASI_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_TUGAS_TAMBAHAN_GURU',
        ),
        migrations.RemoveField(
            model_name='dataguru',
            name='DATA_TUNJANGAN_GURU',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_ANAK_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_BEASISWA_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_BUKU_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_DIKLAT_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_KARYA_TULIS_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_KESEJAHTERAAN_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_KOMPETENSI_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_NILAI_TEST_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_PENDIDIKAN_NORMAL_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_PENGHARGAAN_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_RIWAYAT_GAJI_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_RIWAYAT_JABATAN_FUNGSIONAL_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_RIWAYAT_JABATAN_STRUKTURAL_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_RIWAYAT_KARIR_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_RIWAYAT_KEPANGKATAN_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_SERTIFIKASI_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_TUGAS_TAMBAHAN_KARYAWAN',
        ),
        migrations.RemoveField(
            model_name='datakaryawan',
            name='DATA_TUNJANGAN_KARYAWAN',
        ),
        migrations.DeleteModel(
            name='DataAnakPegawai',
        ),
        migrations.DeleteModel(
            name='DataBeasiswaPegawai',
        ),
        migrations.DeleteModel(
            name='DataBukuPegawai',
        ),
        migrations.DeleteModel(
            name='DataDiklatPegawai',
        ),
        migrations.DeleteModel(
            name='DataKaryaTulisPegawai',
        ),
        migrations.DeleteModel(
            name='DataKesejahteraanPegawai',
        ),
        migrations.DeleteModel(
            name='DataKompetensiPegawai',
        ),
        migrations.DeleteModel(
            name='DataNilaiTesPegawai',
        ),
        migrations.DeleteModel(
            name='DataPenghargaanPegawai',
        ),
        migrations.DeleteModel(
            name='DataRiwayatGajiBerkalaPegawai',
        ),
        migrations.DeleteModel(
            name='DataRiwayatJabatanFungsionalPegawai',
        ),
        migrations.DeleteModel(
            name='DataRiwayatJabatanStrukturalPegawai',
        ),
        migrations.DeleteModel(
            name='DataRiwayatKarirGuruPegawai',
        ),
        migrations.DeleteModel(
            name='DataRiwayatKepangkatanPegawai',
        ),
        migrations.DeleteModel(
            name='DataRiwayatPendidikanFormalPegawai',
        ),
        migrations.DeleteModel(
            name='DataRiwayatSertifikasiPegawai',
        ),
        migrations.DeleteModel(
            name='DataTugasTambahanPegawai',
        ),
        migrations.DeleteModel(
            name='DataTunjanganPegawai',
        ),
        migrations.AddField(
            model_name='datatunjangankaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datatunjanganguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datatugastambahankaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datatugastambahanguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datariwayatsertifikasikaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datariwayatsertifikasiguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datariwayatpendidikanformalkaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datariwayatpendidikanformalguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datariwayatkepangkatankaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datariwayatkepangkatanguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datariwayatkarirkaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datariwayatkarirguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datariwayatjabatanstrukturalkaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datariwayatjabatanstrukturalguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datariwayatjabatanfungsionalkaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datariwayatjabatanfungsionalguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datariwayatgajiberkalakaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datariwayatgajiberkalaguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datapenghargaankaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datapenghargaanguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datanilaiteskaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datanilaitesguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datakompetensikaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datakompetensiguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datakesejahteraankaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datakesejahteraanguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datakaryatuliskaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datakaryatulisguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='datadiklatkaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='datadiklatguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='databukukaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='databukuguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='databeasiswakaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='databeasiswaguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
        migrations.AddField(
            model_name='dataanakkaryawan',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datakaryawan'),
        ),
        migrations.AddField(
            model_name='dataanakguru',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprofil.dataguru'),
        ),
    ]
