# Generated by Django 4.0 on 2021-12-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0014_dataanakguru_dataanakkaryawan_databeasiswaguru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataanakguru',
            options={'verbose_name_plural': 'Data Anak Guru'},
        ),
        migrations.AlterModelOptions(
            name='dataanakkaryawan',
            options={'verbose_name_plural': 'Data Anak Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='databeasiswaguru',
            options={'verbose_name_plural': 'Data Beasiswa Guru'},
        ),
        migrations.AlterModelOptions(
            name='databeasiswakaryawan',
            options={'verbose_name_plural': 'Data Beasiswa Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='databukuguru',
            options={'verbose_name_plural': 'Data Buku Guru'},
        ),
        migrations.AlterModelOptions(
            name='databukukaryawan',
            options={'verbose_name_plural': 'Data Buku Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datadiklatguru',
            options={'verbose_name_plural': 'Data Diklat Guru'},
        ),
        migrations.AlterModelOptions(
            name='datadiklatkaryawan',
            options={'verbose_name_plural': 'Data Diklat Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datakaryatulisguru',
            options={'verbose_name_plural': 'Data Karya Tulis Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datakaryatuliskaryawan',
            options={'verbose_name_plural': 'Data Karya Tulis Guru'},
        ),
        migrations.AlterModelOptions(
            name='datakesejahteraanguru',
            options={'verbose_name_plural': 'Data Kesejahteraan Guru'},
        ),
        migrations.AlterModelOptions(
            name='datakesejahteraankaryawan',
            options={'verbose_name_plural': 'Data Kesejahteraan Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datakompetensiguru',
            options={'verbose_name_plural': 'Data Kompetensi Guru'},
        ),
        migrations.AlterModelOptions(
            name='datakompetensikaryawan',
            options={'verbose_name_plural': 'Data Kompetensi Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datanilaitesguru',
            options={'verbose_name_plural': 'Data Nilai Test Guru'},
        ),
        migrations.AlterModelOptions(
            name='datanilaiteskaryawan',
            options={'verbose_name_plural': 'Data Nilai Test Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datapenghargaanguru',
            options={'verbose_name_plural': 'Data Penghargaan Guru'},
        ),
        migrations.AlterModelOptions(
            name='datapenghargaankaryawan',
            options={'verbose_name_plural': 'Data Penghargaan Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatgajiberkalaguru',
            options={'verbose_name_plural': 'Data Riwayat Gaji Berkala Guru'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatgajiberkalakaryawan',
            options={'verbose_name_plural': 'Data Riwayat Gaji Berkala Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatjabatanfungsionalguru',
            options={'verbose_name_plural': 'Data Riwayat Jabatan Fungsional Guru'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatjabatanfungsionalkaryawan',
            options={'verbose_name_plural': 'Data Riwayat Jabatan Fungsional Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatjabatanstrukturalguru',
            options={'verbose_name_plural': 'Data Riwayat Jabatan Struktural Guru'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatjabatanstrukturalkaryawan',
            options={'verbose_name_plural': 'Data Riwayat Jabatan Struktural Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatkarirguru',
            options={'verbose_name_plural': 'Data Riwayat Karir Guru Guru'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatkarirkaryawan',
            options={'verbose_name_plural': 'Data Riwayat Karir Karyawan '},
        ),
        migrations.AlterModelOptions(
            name='datariwayatkepangkatanguru',
            options={'verbose_name_plural': 'Data Riwayat Kepangkatan Guru'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatkepangkatankaryawan',
            options={'verbose_name_plural': 'Data Riwayat Kepangkatan Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatpendidikanformalguru',
            options={'verbose_name_plural': 'Data Riwayat Pendidikan Formal Guru'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatpendidikanformalkaryawan',
            options={'verbose_name_plural': 'Data Riwayat Pendidikan Formal Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatsertifikasiguru',
            options={'verbose_name_plural': 'Data Riwayat Sertifikasi Guru'},
        ),
        migrations.AlterModelOptions(
            name='datariwayatsertifikasikaryawan',
            options={'verbose_name_plural': 'Data Riwayat Sertifikasi Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datatugastambahanguru',
            options={'verbose_name_plural': 'Data Tugas Tambahan Guru'},
        ),
        migrations.AlterModelOptions(
            name='datatugastambahankaryawan',
            options={'verbose_name_plural': 'Data Tugas Tambahan Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='datatunjanganguru',
            options={'verbose_name_plural': 'Data Tunjangan Guru'},
        ),
        migrations.AlterModelOptions(
            name='datatunjangankaryawan',
            options={'verbose_name_plural': 'Data Tunjangan Karyawan'},
        ),
    ]
