# Generated by Django 4.0 on 2021-12-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0015_alter_dataanakguru_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datakaryatulisguru',
            options={'verbose_name_plural': 'Data Karya Tulis Guru'},
        ),
        migrations.AlterModelOptions(
            name='datakesejahteraanguru',
            options={'verbose_name_plural': 'Data Kesejahteraan Karyawan'},
        ),
    ]
