# Generated by Django 4.0 on 2021-12-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0016_alter_datakaryatulisguru_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataorangtua',
            name='NIK_AYAH',
            field=models.BigIntegerField(default=122122),
            preserve_default=False,
        ),
    ]
