# Generated by Django 4.0 on 2021-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0018_alter_datasiswa_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='NAMA',
            field=models.CharField(max_length=225),
        ),
    ]
