# Generated by Django 4.0 on 2022-01-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0019_alter_datasiswa_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakompetensiguru',
            name='BIDANG_STUDI',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='datakompetensiguru',
            name='URUTAN',
            field=models.CharField(max_length=225),
        ),
    ]
