# Generated by Django 4.0 on 2022-01-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0020_alter_datakompetensiguru_bidang_studi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakompetensiguru',
            name='BIDANG_STUDI',
            field=models.CharField(help_text='Bidang studi', max_length=225),
        ),
    ]
