# Generated by Django 4.0 on 2022-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0021_alter_datakompetensiguru_bidang_studi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataguru',
            name='STATUS_AKTIF',
            field=models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], max_length=14),
        ),
        migrations.AlterField(
            model_name='datakaryawan',
            name='STATUS_AKTIF',
            field=models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], max_length=14),
        ),
    ]
