# Generated by Django 4.0 on 2022-01-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0022_alter_dataguru_status_aktif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorangtua',
            name='DATA_ANAK',
            field=models.ManyToManyField(blank=True, to='dataprofil.DataSiswa', verbose_name='DAFTAR ANAK'),
        ),
    ]
