# Generated by Django 4.0 on 2022-03-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pembayaran',
        ),
    ]
