# Generated by Django 4.0 on 2022-03-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0001_initial'),
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='NAMA_SISWA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kelassiswa'),
            preserve_default=False,
        ),
    ]
