# Generated by Django 4.0 on 2022-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0003_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='KUITANSI',
            field=models.FileField(blank=True, max_length=255, upload_to='DataKeuangan'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='JENIS_PEMBAYARAN',
            field=models.CharField(choices=[('SPP', 'SPP'), ('Dana Peran Serta Masyarakat Rutin', 'Dana Peran Serta Masyarakat Rutin'), ('Dana Peran Serta Masyarakat Insindental', 'Dana Peran Serta Masyarakat Insindental'), ('Bimbel', 'Bimbel')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_BULAN',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='JenisPembayaran',
        ),
    ]
