# Generated by Django 4.0 on 2022-03-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0004_pembayaran_kuitansi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='TEMPLATE',
            field=models.FileField(blank=True, max_length=255, upload_to='DataKeuangan'),
        ),
    ]
