# Generated by Django 4.0 on 2022-03-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0005_pembayaran_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuitansiPembayaranProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Kwitansi Pembayaran',
                'ordering': ['NAMA_SISWA'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keuangan.pembayaran',),
        ),
    ]
