# Generated by Django 4.0 on 2022-03-28 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofil', '0001_initial'),
        ('kurikulum', '0001_initial'),
        ('keuangan', '0008_delete_kuitansipembayaranproxy_pembayaran_generate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='NAMA_SISWA',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='DATA_SISWA',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dataprofil.datasiswa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='KELAS',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.offeringkelas'),
            preserve_default=False,
        ),
    ]
