# Generated by Django 4.0 on 2022-03-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0010_remove_pembayaran_data_siswa_remove_pembayaran_kelas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='JENIS_PEMBAYARAN',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
