# Generated by Django 4.0 on 2022-03-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0011_alter_pembayaran_jenis_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_BULAN',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
