# Generated by Django 4.0 on 2022-03-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0012_alter_pembayaran_pembayaran_bulan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='JENIS_PEMBAYARAN',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='NOMINAL_PEMBAYARAN',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='BIMBEL',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_INSINDENTAL',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_RUTIN',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
