# Generated by Django 4.0 on 2022-03-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0013_remove_pembayaran_jenis_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='BIMBEL',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_INSINDENTAL',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_RUTIN',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
