# Generated by Django 4.0 on 2022-03-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0014_alter_pembayaran_bimbel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='NOMINAL_SPP',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='BIMBEL',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_INSINDENTAL',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_RUTIN',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
