# Generated by Django 4.0 on 2022-03-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0015_pembayaran_nominal_spp_alter_pembayaran_bimbel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembayaran',
            old_name='PEMBAYARAN_BULAN',
            new_name='PEMBAYARAN_SPP',
        ),
    ]
