# Generated by Django 4.0 on 2022-03-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0016_rename_pembayaran_bulan_pembayaran_pembayaran_spp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='BIMBEL',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='NOMINAL_SPP',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_INSINDENTAL',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_RUTIN',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_SPP',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
