# Generated by Django 4.0 on 2022-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0017_alter_pembayaran_bimbel_alter_pembayaran_nominal_spp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='BULAN',
            field=models.CharField(blank=True, choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('Semester', 'Semester'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='TAHUN',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
