# Generated by Django 4.0 on 2022-04-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0018_pembayaran_bulan_pembayaran_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='BULAN',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='TAHUN',
        ),
    ]
