# Generated by Django 4.0 on 2022-04-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0019_remove_pembayaran_bulan_remove_pembayaran_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='TEMPLATE',
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='BIMBEL',
            field=models.CharField(blank=True, default=0, max_length=1024),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='NOMINAL_SPP',
            field=models.CharField(blank=True, default=0, max_length=1024),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_INSINDENTAL',
            field=models.CharField(blank=True, default=0, max_length=1024),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='PEMBAYARAN_DPSM_RUTIN',
            field=models.CharField(blank=True, default=0, max_length=1024),
        ),
    ]
